/* FILE GENERATED AUTOMATICALLY */

export type BuddyType =
    | "RGX 11z Pro Buddy"
    | "Gaia's Vengeance Buddy"
    | "Zedd Buddy"
    | "Get Carried Buddy"
    | "Big Brain Buddy"
    | "In A Bind Buddy"
    | "Year One Buddy"
    | "BlastX Buddy"
    | "Boba Buddy"
    | "Hammer Time Buddy"
    | "Big ol' Barrel Buddy"
    | "Easy Breezy Buddy"
    | "Bruno Coin Buddy"
    | "Epilogue: Bruno Coin Buddy"
    | "Eco the Bulldog Buddy"
    | "Epilogue: Eco the Bulldog Buddy"
    | "Bullet Buddy"
    | "Call Me Buddy"
    | "Get The Picture Buddy"
    | "Edible Ornament Buddy"
    | "Closed Beta Coin Buddy"
    | "VALORANT GO! Vol. 1 Cypher Buddy"
    | "VALORANT GO! Vol. 1 Jett Buddy"
    | "VALORANT GO! Vol. 1 Killjoy Buddy"
    | "VALORANT GO! Vol. 2 Phoenix Buddy"
    | "VALORANT GO! Vol. 2 Raze Buddy"
    | "VALORANT GO! Vol. 1 Reyna Buddy"
    | "VALORANT GO! Vol. 1 Sage Buddy"
    | "VALORANT GO! Vol. 2 Sova Buddy"
    | "VALORANT GO! Vol. 2 Viper Buddy"
    | "VALORANT GO! Vol. 2 Yoru Buddy"
    | "Winner Winner Buddy"
    | "Chicken Out Buddy"
    | "Origin Buddy"
    | "Blast Pin Buddy"
    | "Island Dreams Buddy"
    | "EP 1 // 1 Coin Buddy"
    | "EP 1 // 2 Coin Buddy"
    | "EP 1 // 3 Coin Buddy"
    | "EP 2 // 1 Coin Buddy"
    | "EP 2 // 2 Coin Buddy"
    | "EP 2 // 3 Coin Buddy"
    | "EP 3 // 1 Coin Buddy"
    | "Ep 3 // 2 Coin Buddy"
    | "Ep 3 // 3 Coin Buddy"
    | "Ep 4 // 1 Coin Buddy"
    | "Ep 4 // 2 Coin Buddy"
    | "Follow Me Buddy"
    | "Chilly McFreeze Buddy"
    | "Crate Buddy"
    | "Radianite Crate Buddy"
    | "Red Alert Buddy"
    | "Cup o' Crown Buddy"
    | "Arcane Cupcake Buddy"
    | "Divine Swine Buddy"
    | "Glitchpop Buddy"
    | "Glitchpop, EP 2 Buddy"
    | "Danger Lizard Buddy"
    | "Lucky Dice Buddy"
    | "Discotech Buddy"
    | "Epilogue: Discotech Buddy"
    | "Donut Buddy"
    | "Elderflame Buddy"
    | "VLT/R Buddy"
    | "Happy Dumpling Buddy"
    | "Dumpster Fire Buddy"
    | "Epilogue: Dumpster Fire Buddy"
    | "Singularity Buddy"
    | "Songsteel Buddy"
    | "Together Forever Buddy"
    | "2021 VCT Champions Winner Buddy"
    | "2021 VCT Masters Winner Buddy"
    | "VCT 2021 Spark Buddy"
    | "Good Boy, Bruno Buddy"
    | "Nice Smile Buddy"
    | "Forsaken Buddy"
    | "Velocity Buddy"
    | "Lunar Firework Buddy"
    | "Ascent Rising Buddy"
    | "Arcane Poro Buddy"
    | "Team Ace Buddy"
    | "KNG Meridian Buddy"
    | "Le Baguette Buddy"
    | "Froggie Hat Buddy"
    | "Spectrum Buddy"
    | "Gelato Cutie Buddy"
    | "Tall Tales Buddy"
    | "Give Back Buddy"
    | "Caught Buddy"
    | "Ruin Watcher Buddy"
    | "Memory Chip Buddy"
    | "Hawko Buddy"
    | "White Hat Buddy"
    | "Safe Haven Buddy"
    | "Xpert Comms Buddy"
    | "Owl Charm Buddy"
    | "Hydrodip Buddy"
    | "Prime Buddy"
    | "Prime//2.0 Buddy"
    | "Icy Crate Buddy"
    | "Mi Goreng Buddy"
    | "Jack O' Lantern Buddy"
    | "The Key to Ancient Mysteries Buddy"
    | "Key of Life Buddy"
    | "Bot Buddy"
    | "Netter Treter Buddy"
    | "Ruination Buddy"
    | "K/TAC Buddy"
    | "Kingdom Logo Buddy"
    | "Dance of Luck Buddy"
    | "GL Have Cat Buddy"
    | "Celestial Buddy"
    | "Magepunk Buddy"
    | "Spline Buddy"
    | "Magic Mance Buddy"
    | "Mango Tango Buddy"
    | "Time's Up Buddy"
    | "Dallah Buddy"
    | "Mic Drop Buddy"
    | "Monkey Business Buddy"
    | "Matryoshka Buddy"
    | "Genesis Buddy"
    | "Salmon Nigiri Buddy"
    | "Deadly Precision Buddy"
    | "Ion Buddy"
    | "Ancient Mysteries Revealed Buddy"
    | "VALORANT Coin Buddy"
    | "Oni Buddy"
    | "Keep it Safe Buddy"
    | "Keep it Safer Buddy"
    | "Venom Vial Buddy"
    | "Dan the Penguin Buddy"
    | "Hot Bling Buddy"
    | "High Top Heat Buddy"
    | "Old Salt Buddy"
    | "Pizza Buddy"
    | "Magepunk, Ep 3 Buddy"
    | "POLYfox Buddy"
    | "Rubber Ducky Buddy"
    | "Artisan Buddy"
    | "Take on the Tundra Buddy"
    | "Pay Respects Buddy"
    | "One Direction Buddy"
    | "Protocol 781-A Buddy"
    | "Lovebyte Gun Buddy"
    | "Lucky Rabbit Buddy"
    | "Radianite Crystal Buddy"
    | "Late Night Calories Buddy"
    | "EP1: Bronze Buddy"
    | "EP1: Diamond Buddy"
    | "EP1: Gold Buddy"
    | "EP1: Immortal Buddy"
    | "EP1: Iron Buddy"
    | "EP1: Platinum Buddy"
    | "EP1: Radiant Buddy"
    | "EP1: Silver Buddy"
    | "EP2: Bronze Buddy"
    | "EP2: Diamond Buddy"
    | "EP2: Gold Buddy"
    | "EP2: Immortal Buddy"
    | "EP2: Iron Buddy"
    | "EP2: Platinum Buddy"
    | "EP2: Radiant Buddy"
    | "EP2: Silver Buddy"
    | "EP3: Bronze Buddy"
    | "EP3: Diamond Buddy"
    | "EP3: Gold Buddy"
    | "EP3: Immortal Buddy"
    | "EP3: Iron Buddy"
    | "EP3: Platinum Buddy"
    | "EP3: Radiant Buddy"
    | "EP3: Silver Buddy"
    | "Gravitational Uranium Neuroblaster Buddy"
    | "Stardust Buddy"
    | "Root Beer Buddy"
    | "Immortal Rose Buddy"
    | "Salt Shaker Buddy"
    | "Epilogue: Salt Shaker Buddy"
    | "Ancient Inheritance Buddy"
    | "Dog Tags Buddy"
    | "Fishbones Buddy"
    | "Lycan's Bane Buddy"
    | "All-purpose Slipper Buddy"
    | "Snowbro Buddy"
    | "Snowfall Buddy"
    | "Sentinels of Light Buddy"
    | "Reaver Buddy"
    | "Sovereign Buddy"
    | "Hot Take Buddy"
    | "The Spike Buddy"
    | "Spike Rush Buddy"
    | "Split Decision Buddy"
    | "Battle Crab Buddy"
    | "Surge Protector Buddy"
    | "Dimensional Fragment Buddy"
    | "Sock of Cheer Buddy"
    | "Cheesed Buddy"
    | "Bear Tactics Buddy"
    | "Bunny Tactics Buddy"
    | "Squirrel Tactics Buddy"
    | "Potato Aim Buddy"
    | "Sample 36-K Buddy"
    | "Radianite Orb Buddy"
    | "Tigris Buddy"
    | "Toaster Buddy"
    | "Scuttle Trash Buddy"
    | "Fist Bump Buddy"
    | "Turtle Ship Buddy"
    | "No. 1 Fan Buddy"
    | "Tower of Power Buddy"
    | "Outta This World Buddy"
    | "Ego Buddy"
    | "Exquisitely Wrapped Buddy"
    | "The Wheel of Steel Buddy"
    | "Soul Capsule Buddy"
    | "Grim Delight Buddy"
    | "Pocket Knife Buddy"
    | "Zoomer Pop Buddy";
