/* FILE GENERATED AUTOMATICALLY */

export type BuddyType =
    | "Zedd Buddy"
    | "Get Carried Buddy"
    | "In A Bind Buddy"
    | "Year One Buddy"
    | "BlastX Buddy"
    | "Boba Buddy"
    | "Hammer Time Buddy"
    | "Bruno Coin Buddy"
    | "Epilogue: Bruno Coin Buddy"
    | "Bullet Buddy"
    | "Closed Beta Coin Buddy"
    | "VALORANT GO! Vol. 1 Cypher Buddy"
    | "VALORANT GO! Vol. 1 Jett Buddy"
    | "VALORANT GO! Vol. 1 Killjoy Buddy"
    | "VALORANT GO! Vol. 2 Phoenix Buddy"
    | "VALORANT GO! Vol. 2 Raze Buddy"
    | "VALORANT GO! Vol. 1 Reyna Buddy"
    | "VALORANT GO! Vol. 1 Sage Buddy"
    | "VALORANT GO! Vol. 2 Sova Buddy"
    | "VALORANT GO! Vol. 2 Viper Buddy"
    | "VALORANT GO! Vol. 2 Yoru Buddy"
    | "Origin Buddy"
    | "Blast Pin Buddy"
    | "Island Dreams Buddy"
    | "EP 1 // 1 Coin Buddy"
    | "EP 1 // 2 Coin Buddy"
    | "EP 1 // 3 Coin Buddy"
    | "EP 2 // 1 Coin Buddy"
    | "EP 2 // 2 Coin Buddy"
    | "EP 2 // 3 Coin Buddy"
    | "EP 3 // 1 Coin Buddy"
    | "Ep 3 // 2 Coin Buddy"
    | "Follow Me Buddy"
    | "Chilly McFreeze Buddy"
    | "Crate Buddy"
    | "Radianite Crate Buddy"
    | "Red Alert Buddy"
    | "Cup o' Crown Buddy"
    | "Glitchpop Buddy"
    | "Glitchpop, EP 2 Buddy"
    | "Danger Lizard Buddy"
    | "Lucky Dice Buddy"
    | "Discotech Buddy"
    | "Epilogue: Discotech Buddy"
    | "Donut Buddy"
    | "Elderflame Buddy"
    | "VLT/R Buddy"
    | "Singularity Buddy"
    | "Songsteel Buddy"
    | "2021 VCT Masters Winner Buddy"
    | "Good Boy, Bruno Buddy"
    | "Nice Smile Buddy"
    | "Forsaken Buddy"
    | "Lunar Firework Buddy"
    | "Ascent Rising Buddy"
    | "KNG Meridian Buddy"
    | "Froggie Hat Buddy"
    | "Spectrum Buddy"
    | "Gelato Cutie Buddy"
    | "Tall Tales Buddy"
    | "Give Back Buddy"
    | "Caught Buddy"
    | "Ruin Watcher Buddy"
    | "Memory Chip Buddy"
    | "Hawko Buddy"
    | "White Hat Buddy"
    | "Safe Haven Buddy"
    | "Xpert Comms Buddy"
    | "Owl Charm Buddy"
    | "Prime Buddy"
    | "Prime//2.0 Buddy"
    | "Icy Crate Buddy"
    | "Jack O' Lantern Buddy"
    | "The Key to Ancient Mysteries Buddy"
    | "Bot Buddy"
    | "Netter Treter Buddy"
    | "Ruination Buddy"
    | "K/TAC Buddy"
    | "Kingdom Logo Buddy"
    | "GL Have Cat Buddy"
    | "Celestial Buddy"
    | "Magepunk Buddy"
    | "Spline Buddy"
    | "Mango Tango Buddy"
    | "Time's Up Buddy"
    | "Dallah Buddy"
    | "Mic Drop Buddy"
    | "Salmon Nigiri Buddy"
    | "Deadly Precision Buddy"
    | "Ion Buddy"
    | "Ancient Mysteries Revealed Buddy"
    | "VALORANT Coin Buddy"
    | "Oni Buddy"
    | "Keep it Safe Buddy"
    | "Venom Vial Buddy"
    | "Dan the Penguin Buddy"
    | "Hot Bling Buddy"
    | "High Top Heat Buddy"
    | "Old Salt Buddy"
    | "Pizza Buddy"
    | "POLYfox Buddy"
    | "Rubber Ducky Buddy"
    | "Artisan Buddy"
    | "Take on the Tundra Buddy"
    | "Pay Respects Buddy"
    | "One Direction Buddy"
    | "Lovebyte Gun Buddy"
    | "Lucky Rabbit Buddy"
    | "Radianite Crystal Buddy"
    | "Late Night Calories Buddy"
    | "EP1: Bronze Buddy"
    | "EP1: Diamond Buddy"
    | "EP1: Gold Buddy"
    | "EP1: Immortal Buddy"
    | "EP1: Iron Buddy"
    | "EP1: Platinum Buddy"
    | "EP1: Radiant Buddy"
    | "EP1: Silver Buddy"
    | "EP2: Bronze Buddy"
    | "EP2: Diamond Buddy"
    | "EP2: Gold Buddy"
    | "EP2: Immortal Buddy"
    | "EP2: Iron Buddy"
    | "EP2: Platinum Buddy"
    | "EP2: Radiant Buddy"
    | "EP2: Silver Buddy"
    | "Gravitational Uranium Neuroblaster Buddy"
    | "Stardust Buddy"
    | "Root Beer Buddy"
    | "Immortal Rose Buddy"
    | "Salt Shaker Buddy"
    | "Epilogue: Salt Shaker Buddy"
    | "Ancient Inheritance Buddy"
    | "Dog Tags Buddy"
    | "Snowbro Buddy"
    | "Sentinels of Light Buddy"
    | "Reaver Buddy"
    | "Sovereign Buddy"
    | "Hot Take Buddy"
    | "The Spike Buddy"
    | "Spike Rush Buddy"
    | "Split Decision Buddy"
    | "Battle Crab Buddy"
    | "Dimensional Fragment Buddy"
    | "Cheesed Buddy"
    | "Bear Tactics Buddy"
    | "Squirrel Tactics Buddy"
    | "Potato Aim Buddy"
    | "Sample 36-K Buddy"
    | "Radianite Orb Buddy"
    | "Toaster Buddy"
    | "Scuttle Trash Buddy"
    | "Fist Bump Buddy"
    | "No. 1 Fan Buddy"
    | "Tower of Power Buddy"
    | "Ego Buddy"
    | "The Wheel of Steel Buddy"
    | "Soul Capsule Buddy"
    | "Grim Delight Buddy"
    | "Pocket Knife Buddy"
    | "Zoomer Pop Buddy";
