/* FILE GENERATED AUTOMATICALLY */

export type VariantSkin<T> = T extends "Glitchpop Odin"
    ? "Default" | "Blue" | "Red" | "Gold"
    : T extends "Nitro Odin"
    ? "Default"
    : T extends "dot EXE Odin"
    ? "Default"
    : T extends "Prime//2.0 Odin"
    ? "Default" | "Gold" | "Green" | "Orange"
    : T extends "Prism III Odin"
    ? "Default" | "Pink" | "Green" | "Purple"
    : T extends "Smite Odin"
    ? "Default"
    : T extends "Sensation Odin"
    ? "Default"
    : T extends "Lightwave Odin"
    ? "Default" | "Blue" | "Red" | "Gray"
    : T extends "Schema Odin"
    ? "Default"
    : T extends "Standard Odin"
    ? "Default"
    : T extends "Aerosol Odin"
    ? "Default"
    : T extends "BlastX Odin"
    ? "Default" | "Black" | "Yellow" | "Pink"
    : T extends "VALORANT GO! Vol. 2 Ares"
    ? "Default"
    : T extends "Aristocrat Ares"
    ? "Default"
    : T extends "Nebula Ares"
    ? "Default"
    : T extends "Singularity Ares"
    ? "Default" | "Blue" | "Red" | "Purple"
    : T extends "Rush Ares"
    ? "Default"
    : T extends "Hivemind Ares"
    ? "Default"
    : T extends "Infantry Ares"
    ? "Default"
    : T extends "Goldwing Ares"
    ? "Default"
    : T extends "Outpost Ares"
    ? "Default"
    : T extends "Prism Ares"
    ? "Default"
    : T extends "Nunca Olvidados Ares"
    ? "Default" | "Living" | "Eternal"
    : T extends "Celestial Ares"
    ? "Default"
    : T extends "Magepunk Ares"
    ? "Default" | "Green" | "Pink" | "Orange"
    : T extends "Minima Ares"
    ? "Default"
    : T extends "POLYfrog Ares"
    ? "Default"
    : T extends "Jigsaw Ares"
    ? "Default" | "Killjoy" | "Astra" | "Yoru"
    : T extends "Sakura Ares"
    ? "Default"
    : T extends "Snowfall Ares"
    ? "Default"
    : T extends "Sentinels of Light Ares"
    ? "Default" | "Pink" | "Red/Green" | "Blue/Purple"
    : T extends "Standard Ares"
    ? "Default"
    : T extends "RGX 11z Pro Vandal"
    ? "Default" | "Red" | "Blue" | "Yellow"
    : T extends "VALORANT GO! Vol. 2 Vandal"
    ? "Default"
    : T extends "Aristocrat Vandal"
    ? "Default"
    : T extends "Champions 2021 Vandal"
    ? "Default"
    : T extends "Origin Vandal"
    ? "Default" | "Green" | "Red" | "White"
    : T extends "Glitchpop Vandal"
    ? "Default" | "Blue" | "Red" | "Gold"
    : T extends "Elderflame Vandal"
    ? "Default" | "Red" | "Blue" | "Dark"
    : T extends "Nitro Vandal"
    ? "Default"
    : T extends "Hivemind Vandal"
    ? "Default"
    : T extends "Forsaken Vandal"
    ? "Default" | "Gold"
    : T extends "Ruin Vandal"
    ? "Default"
    : T extends "dot EXE Vandal"
    ? "Default"
    : T extends "Horizon Vandal"
    ? "Default"
    : T extends "Prime Vandal"
    ? "Default" | "Orange" | "Blue" | "Yellow"
    : T extends "Avalanche Vandal"
    ? "Default"
    : T extends "Prism II Vandal"
    ? "Default"
    : T extends "K/TAC Vandal"
    ? "Default"
    : T extends "Nunca Olvidados Vandal"
    ? "Default" | "Living" | "Eternal"
    : T extends "Luxe Vandal"
    ? "Default"
    : T extends "Silvanus Vandal"
    ? "Default"
    : T extends "Sensation Vandal"
    ? "Default"
    : T extends "Sakura Vandal"
    ? "Default"
    : T extends "Schema Vandal"
    ? "Default"
    : T extends "Sentinels of Light Vandal"
    ? "Default" | "Pink" | "Red/Green" | "Blue/Purple"
    : T extends "Reaver Vandal"
    ? "Default" | "Red" | "Black" | "White"
    : T extends "Tethered Realms Vandal"
    ? "Default"
    : T extends "Cavalier Vandal"
    ? "Default"
    : T extends "Standard Vandal"
    ? "Default"
    : T extends "Depths Vandal"
    ? "Default"
    : T extends "Ego Vandal"
    ? "Default" | "Red" | "Tan" | "Pink"
    : T extends "Wasteland Vandal"
    ? "Default"
    : T extends "Winterwunderland Vandal"
    ? "Default"
    : T extends "Aristocrat Bulldog"
    ? "Default"
    : T extends "Spectrum Bulldog"
    ? "Default" | "Black" | "Red" | "Purple/Pink"
    : T extends "Undercity Bulldog"
    ? "Default"
    : T extends "Glitchpop Bulldog"
    ? "Default" | "Blue" | "Red" | "Gold"
    : T extends "Rush Bulldog"
    ? "Default"
    : T extends "Velocity Bulldog"
    ? "Default" | "Yellow" | "Purple" | "Aquamarine"
    : T extends "Horizon Bulldog"
    ? "Default"
    : T extends "K/TAC Bulldog"
    ? "Default"
    : T extends "Couture Bulldog"
    ? "Default"
    : T extends "Nunca Olvidados Bulldog"
    ? "Default" | "Living" | "Eternal"
    : T extends "Genesis Bulldog"
    ? "Default"
    : T extends "POLYfox Bulldog"
    ? "Default"
    : T extends "Protocol 781-A Bulldog"
    ? "Default" | "White/Pink" | "Red/Blue" | "Green"
    : T extends "Infinity Bulldog"
    ? "Default" | "White" | "Yellow" | "Pink"
    : T extends "Standard Bulldog"
    ? "Default"
    : T extends "Convex Bulldog"
    ? "Default"
    : T extends "Depths Bulldog"
    ? "Default"
    : T extends "Varnish Bulldog"
    ? "Default"
    : T extends "VALORANT GO! Vol. 1 Phantom"
    ? "Default"
    : T extends "Spectrum Phantom"
    ? "Default" | "Black" | "Red" | "Purple/Pink"
    : T extends "Radiant Crisis 001 Phantom"
    ? "Default"
    : T extends "Nebula Phantom"
    ? "Default"
    : T extends "Undercity Phantom"
    ? "Default"
    : T extends "Glitchpop Phantom"
    ? "Default" | "Blue" | "Red" | "Gold"
    : T extends "Singularity Phantom"
    ? "Default" | "Blue" | "Red" | "Purple"
    : T extends "Rush Phantom"
    ? "Default"
    : T extends "Velocity Phantom"
    ? "Default" | "Yellow" | "Purple" | "Aquamarine"
    : T extends "Prime//2.0 Phantom"
    ? "Default" | "Gold" | "Green" | "Orange"
    : T extends "Avalanche Phantom"
    ? "Default"
    : T extends "Prism Phantom"
    ? "Default"
    : T extends "Serenity Phantom"
    ? "Default"
    : T extends "Ruination Phantom"
    ? "Default" | "Purple" | "Red/Yellow" | "Green"
    : T extends "Kingdom Phantom"
    ? "Default"
    : T extends "Smite Phantom"
    ? "Default"
    : T extends "Celestial Phantom"
    ? "Default"
    : T extends "Spline Phantom"
    ? "Default" | "Green" | "Red" | "Blue"
    : T extends "Minima Phantom"
    ? "Default"
    : T extends "Galleria Phantom"
    ? "Default"
    : T extends "Silvanus Phantom"
    ? "Default"
    : T extends "Ion Phantom"
    ? "Default"
    : T extends "Oni Phantom"
    ? "Default" | "Black" | "Green" | "White"
    : T extends "Aero Phantom"
    ? "Default" | "Cream/Pink" | "Purple/Gray" | "Green/Black"
    : T extends "Artisan Phantom"
    ? "Default" | "Red" | "Green" | "Blue"
    : T extends "Protocol 781-A Phantom"
    ? "Default" | "White/Pink" | "Red/Blue" | "Green"
    : T extends "Lightwave Phantom"
    ? "Default" | "Blue" | "Red" | "Gray"
    : T extends "Snowfall Phantom"
    ? "Default"
    : T extends "Recon Phantom"
    ? "Default" | "RedCamo" | "BlueCamo" | "GreenCamo"
    : T extends "Infinity Phantom"
    ? "Default" | "White" | "Yellow" | "Pink"
    : T extends "Standard Phantom"
    ? "Default"
    : T extends "Tigris Phantom"
    ? "Default"
    : T extends "BlastX Phantom"
    ? "Default" | "Black" | "Yellow" | "Pink"
    : T extends "Winterwunderland Phantom"
    ? "Default"
    : T extends "Undercity Judge"
    ? "Default"
    : T extends "Glitchpop Judge"
    ? "Default" | "Blue" | "Red" | "Gold"
    : T extends "Elderflame Judge"
    ? "Default" | "Red" | "Blue" | "Dark"
    : T extends "Rush Judge"
    ? "Default"
    : T extends "dot EXE Judge"
    ? "Default"
    : T extends "Goldwing Judge"
    ? "Default"
    : T extends "Hydrodip Judge"
    ? "Default"
    : T extends "Outpost Judge"
    ? "Default"
    : T extends "Prism III Judge"
    ? "Default" | "Pink" | "Green" | "Purple"
    : T extends "Serenity Judge"
    ? "Default"
    : T extends "Smite Judge"
    ? "Default"
    : T extends "Celestial Judge"
    ? "Default"
    : T extends "Luxe Judge"
    ? "Default"
    : T extends "POLYfox Judge"
    ? "Default"
    : T extends "Jigsaw Judge"
    ? "Default" | "Skye" | "Astra" | "Yoru"
    : T extends "Sensation Judge"
    ? "Default"
    : T extends "Snowfall Judge"
    ? "Default"
    : T extends "Standard Judge"
    ? "Default"
    : T extends "Convex Judge"
    ? "Default"
    : T extends "Varnish Judge"
    ? "Default"
    : T extends "Origin Bucky"
    ? "Default" | "Green" | "Red" | "White"
    : T extends "Radiant Crisis 001 Bucky"
    ? "Default"
    : T extends "Red Alert Bucky"
    ? "Default"
    : T extends "Surge Bucky"
    ? "Default" | "Black" | "Yellow" | "Blue"
    : T extends "Horizon Bucky"
    ? "Default"
    : T extends "Monarch Bucky"
    ? "Default"
    : T extends "Hydrodip Bucky"
    ? "Default"
    : T extends "Prime//2.0 Bucky"
    ? "Default" | "Gold" | "Green" | "Orange"
    : T extends "Prism II Bucky"
    ? "Default"
    : T extends "Kingdom Bucky"
    ? "Default"
    : T extends "Magepunk Bucky"
    ? "Default" | "Green" | "Purple" | "Orange"
    : T extends "Galleria Bucky"
    ? "Default"
    : T extends "Genesis Bucky"
    ? "Default"
    : T extends "Ion Bucky"
    ? "Default"
    : T extends "Oni Bucky"
    ? "Default" | "Black" | "Green" | "White"
    : T extends "Artisan Bucky"
    ? "Default" | "Red" | "Green" | "Blue"
    : T extends "Gravitational Uranium Neuroblaster Bucky"
    ? "Default" | "Chrome" | "Black" | "RWB"
    : T extends "Lightwave Bucky"
    ? "Default" | "Blue" | "Red" | "Gray"
    : T extends "Cavalier Bucky"
    ? "Default"
    : T extends "Standard Bucky"
    ? "Default"
    : T extends "Aerosol Bucky"
    ? "Default"
    : T extends "RGX 11z Pro Frenzy"
    ? "Default" | "Red" | "Blue" | "Yellow"
    : T extends "RagnaRocker Frenzy"
    ? "Default"
    : T extends "Origin Frenzy"
    ? "Default" | "Green" | "Red" | "White"
    : T extends "Glitchpop Frenzy"
    ? "Default" | "Blue" | "Red" | "Gold"
    : T extends "Elderflame Frenzy"
    ? "Default" | "Red" | "Blue" | "Dark"
    : T extends "Rush Frenzy"
    ? "Default"
    : T extends "Swooping Frenzy"
    ? "Default"
    : T extends "Horizon Frenzy"
    ? "Default"
    : T extends "Monarch Frenzy"
    ? "Default"
    : T extends "Hydrodip Frenzy"
    ? "Default"
    : T extends "Prime//2.0 Frenzy"
    ? "Default" | "Gold" | "Green" | "Orange"
    : T extends "Couture Frenzy"
    ? "Default"
    : T extends "Nunca Olvidados Frenzy"
    ? "Default" | "Living" | "Eternal"
    : T extends "Celestial Frenzy"
    ? "Default"
    : T extends "Spitfire Frenzy"
    ? "Default"
    : T extends "Aero Frenzy"
    ? "Default" | "Cream/Pink" | "Purple/Gray" | "Green/Black"
    : T extends "Sensation Frenzy"
    ? "Default"
    : T extends "Lightwave Frenzy"
    ? "Default" | "Blue" | "Red" | "Gray"
    : T extends "Live Wire Frenzy"
    ? "Default"
    : T extends "Standard Frenzy"
    ? "Default"
    : T extends "BlastX Frenzy"
    ? "Default" | "Black" | "Yellow" | "Pink"
    : T extends "VALORANT GO! Vol. 2 Classic"
    ? "Default"
    : T extends "Spectrum Classic"
    ? "Default" | "Black" | "Red" | "Purple/Pink"
    : T extends "Pistolinha Classic"
    ? "Default"
    : T extends "Radiant Crisis 001 Classic"
    ? "Default"
    : T extends "Red Alert Classic"
    ? "Default"
    : T extends "Undercity Classic"
    ? "Default"
    : T extends "Glitchpop Classic"
    ? "Default" | "Blue" | "Red" | "Gold"
    : T extends "Finesse Classic"
    ? "Default"
    : T extends "Surge Classic"
    ? "Default" | "Black" | "Yellow" | "Blue"
    : T extends "Songsteel Classic"
    ? "Default"
    : T extends "Forsaken Classic"
    ? "Default" | "Gold"
    : T extends "FIRE/arm Classic"
    ? "Default"
    : T extends "Goldwing Classic"
    ? "Default"
    : T extends "Prime Classic"
    ? "Default" | "Orange" | "Blue" | "Yellow"
    : T extends "Avalanche Classic"
    ? "Default"
    : T extends "Prism III Classic"
    ? "Default" | "Pink" | "Green" | "Purple"
    : T extends "Kingdom Classic"
    ? "Default"
    : T extends "Smite Classic"
    ? "Default"
    : T extends "Spline Classic"
    ? "Default" | "Green" | "Red" | "Blue"
    : T extends "Galleria Classic"
    ? "Default"
    : T extends "Gravitational Uranium Neuroblaster Classic"
    ? "Default" | "Chrome" | "Black" | "RWB"
    : T extends "Sakura Classic"
    ? "Default"
    : T extends "Snowfall Classic"
    ? "Default"
    : T extends "Infinity Classic"
    ? "Default" | "White" | "Yellow" | "Pink"
    : T extends "Standard Classic"
    ? "Default"
    : T extends "Final Chamber Classic"
    ? "Default"
    : T extends "VALORANT GO! Vol. 1 Ghost"
    ? "Default"
    : T extends "dot EXE Ghost"
    ? "Default"
    : T extends "Hush Ghost"
    ? "Default"
    : T extends "Infantry Ghost"
    ? "Default"
    : T extends "Goldwing Ghost"
    ? "Default"
    : T extends "Outpost Ghost"
    ? "Default"
    : T extends "Prism Ghost"
    ? "Default"
    : T extends "Serenity Ghost"
    ? "Default"
    : T extends "Ruination Ghost"
    ? "Default" | "Purple" | "Red/Yellow" | "Green"
    : T extends "Luxe Ghost"
    ? "Default"
    : T extends "Magepunk Ghost"
    ? "Default" | "Green" | "Purple" | "Orange"
    : T extends "Artisan Ghost"
    ? "Default" | "Red" | "Green" | "Blue"
    : T extends "Jigsaw Ghost"
    ? "Default" | "Skye" | "Killjoy" | "Astra"
    : T extends "Eclipse Ghost"
    ? "Default"
    : T extends "Sovereign Ghost"
    ? "Default" | "Gold" | "Silver" | "Purple"
    : T extends "Tethered Realms Ghost"
    ? "Default"
    : T extends "Recon Ghost"
    ? "Default" | "RedCamo" | "BlueCamo" | "GreenCamo"
    : T extends "Cavalier Ghost"
    ? "Default"
    : T extends "Standard Ghost"
    ? "Default"
    : T extends "Depths Ghost"
    ? "Default"
    : T extends "Ego Ghost"
    ? "Default" | "Red" | "Tan" | "Pink"
    : T extends "Vendetta Ghost"
    ? "Default"
    : T extends "Winterwunderland Ghost"
    ? "Default"
    : T extends "Soul Silencer Ghost"
    ? "Default"
    : T extends "Aristocrat Sheriff"
    ? "Default"
    : T extends "Nebula Sheriff"
    ? "Default"
    : T extends "Singularity Sheriff"
    ? "Default" | "Blue" | "Red" | "Purple"
    : T extends "Surge Sheriff"
    ? "Default" | "Black" | "Yellow" | "Blue"
    : T extends "Protektor Sheriff"
    ? "Default"
    : T extends "Prism II Sheriff"
    ? "Default"
    : T extends "K/TAC Sheriff"
    ? "Default"
    : T extends "Magepunk Sheriff"
    ? "Default" | "Green" | "Pink" | "Orange"
    : T extends "Minima Sheriff"
    ? "Default"
    : T extends "Silvanus Sheriff"
    ? "Default"
    : T extends "Ion Sheriff"
    ? "Default"
    : T extends "POLYfox Sheriff"
    ? "Default"
    : T extends "POLYfrog Sheriff"
    ? "Default"
    : T extends "Protocol 781-A Sheriff"
    ? "Default" | "White/Pink" | "Red/Blue" | "Green"
    : T extends "Lightwave Sheriff"
    ? "Default" | "Blue" | "Red" | "Gray"
    : T extends "Sakura Sheriff"
    ? "Default"
    : T extends "Peacekeeper Sheriff"
    ? "Default"
    : T extends "Schema Sheriff"
    ? "Default"
    : T extends "Sentinels of Light Sheriff"
    ? "Default" | "Pink" | "Red/Green" | "Blue/Purple"
    : T extends "Reaver Sheriff"
    ? "Default" | "Red" | "Black" | "White"
    : T extends "Standard Sheriff"
    ? "Default"
    : T extends "Convex Sheriff"
    ? "Default"
    : T extends "Varnish Sheriff"
    ? "Default"
    : T extends "Wasteland Sheriff"
    ? "Default"
    : T extends "Game Over Sheriff"
    ? "Default"
    : T extends "Arcane Sheriff"
    ? "Default"
    : T extends "Death Wish Sheriff"
    ? "Default"
    : T extends "Hivemind Shorty"
    ? "Default"
    : T extends "Velocity Shorty"
    ? "Default" | "Yellow" | "Purple" | "Aquamarine"
    : T extends "Ruin Shorty"
    ? "Default"
    : T extends "Monarch Shorty"
    ? "Default"
    : T extends "Prism II Shorty"
    ? "Default"
    : T extends "Wunderkind Shorty"
    ? "Default"
    : T extends "Genesis Shorty"
    ? "Default"
    : T extends "Oni Shorty"
    ? "Default" | "Black" | "Green" | "White"
    : T extends "Snakebite Shorty"
    ? "Default"
    : T extends "Standard Shorty"
    ? "Default"
    : T extends "Aerosol Shorty"
    ? "Default"
    : T extends "Tigris Shorty"
    ? "Default"
    : T extends "Wayfinder Shorty"
    ? "Default"
    : T extends "Wasteland Shorty"
    ? "Default"
    : T extends "VALORANT GO! Vol. 2 Operator"
    ? "Default"
    : T extends "Origin Operator"
    ? "Default" | "Green" | "Red" | "White"
    : T extends "Red Alert Operator"
    ? "Default"
    : T extends "Glitchpop Operator"
    ? "Default" | "Blue" | "Red" | "Gold"
    : T extends "Elderflame Operator"
    ? "Default" | "Red" | "Blue" | "Dark"
    : T extends "Nitro Operator"
    ? "Default"
    : T extends "Forsaken Operator"
    ? "Default" | "Gold"
    : T extends "Infantry Operator"
    ? "Default"
    : T extends "Prism Operator"
    ? "Default"
    : T extends "K/TAC Operator"
    ? "Default"
    : T extends "Luxe Operator"
    ? "Default"
    : T extends "Magepunk Operator"
    ? "Default" | "Green" | "Pink" | "Orange"
    : T extends "Spline Operator"
    ? "Default" | "Green" | "Red" | "Blue"
    : T extends "Minima Operator"
    ? "Default"
    : T extends "Silvanus Operator"
    ? "Default"
    : T extends "Genesis Operator"
    ? "Default"
    : T extends "Ion Operator"
    ? "Default"
    : T extends "Gravitational Uranium Neuroblaster Operator"
    ? "Default" | "Chrome" | "Black" | "RWB"
    : T extends "Sentinels of Light Operator"
    ? "Default" | "Pink" | "Red/Green" | "Blue/Purple"
    : T extends "Reaver Operator"
    ? "Default" | "Red" | "Black" | "White"
    : T extends "Tethered Realms Operator"
    ? "Default"
    : T extends "Cavalier Operator"
    ? "Default"
    : T extends "Standard Operator"
    ? "Default"
    : T extends "Aerosol Operator"
    ? "Default"
    : T extends "Tigris Operator"
    ? "Default"
    : T extends "Convex Operator"
    ? "Default"
    : T extends "RGX 11z Pro Guardian"
    ? "Default" | "Red" | "Blue" | "Yellow"
    : T extends "VALORANT GO! Vol. 1 Guardian"
    ? "Default"
    : T extends "Spectrum Guardian"
    ? "Default" | "Black" | "Red" | "Purple/Pink"
    : T extends "Nebula Guardian"
    ? "Default"
    : T extends "Nitro Guardian"
    ? "Default"
    : T extends "Songsteel Guardian"
    ? "Default"
    : T extends "Ruin Guardian"
    ? "Default"
    : T extends "Infantry Guardian"
    ? "Default"
    : T extends "Hydrodip Guardian"
    ? "Default"
    : T extends "Prime Guardian"
    ? "Default" | "Orange" | "Blue" | "Yellow"
    : T extends "Ruination Guardian"
    ? "Default" | "Purple" | "Red/Yellow" | "Green"
    : T extends "Magepunk Guardian"
    ? "Default" | "Green" | "Pink" | "Orange"
    : T extends "Galleria Guardian"
    ? "Default"
    : T extends "Oni Guardian"
    ? "Default" | "Black" | "Green" | "White"
    : T extends "Aero Guardian"
    ? "Default" | "Cream/Pink" | "Purple/Gray" | "Green/Black"
    : T extends "POLYfox Guardian"
    ? "Default"
    : T extends "Jigsaw Guardian"
    ? "Default" | "Skye" | "Killjoy" | "Yoru"
    : T extends "Reaver Guardian"
    ? "Default" | "Red" | "Black" | "White"
    : T extends "Sovereign Guardian"
    ? "Default" | "Gold" | "Silver" | "Purple"
    : T extends "Tethered Realms Guardian"
    ? "Default"
    : T extends "Recon Guardian"
    ? "Default" | "RedCamo" | "BlueCamo" | "GreenCamo"
    : T extends "Infinity Guardian"
    ? "Default" | "White" | "Yellow" | "Pink"
    : T extends "Standard Guardian"
    ? "Default"
    : T extends "Ego Guardian"
    ? "Default" | "Red" | "Tan" | "Pink"
    : T extends "Songsteel Marshal"
    ? "Default"
    : T extends "Ruin Marshal"
    ? "Default"
    : T extends "Monarch Marshal"
    ? "Default"
    : T extends "Avalanche Marshal"
    ? "Default"
    : T extends "Couture Marshal"
    ? "Default"
    : T extends "Magepunk Marshal"
    ? "Default" | "Green" | "Purple" | "Orange"
    : T extends "Galleria Marshal"
    ? "Default"
    : T extends "POLYfrog Marshal"
    ? "Default"
    : T extends "Artisan Marshal"
    ? "Default" | "Red" | "Green" | "Blue"
    : T extends "Sovereign Marshal"
    ? "Default" | "Gold" | "Silver" | "Purple"
    : T extends "Standard Marshal"
    ? "Default"
    : T extends "Wasteland Marshal"
    ? "Default"
    : T extends "Winterwunderland Marshal"
    ? "Default"
    : T extends "VALORANT GO! Vol. 1 Spectre"
    ? "Default"
    : T extends "Radiant Crisis 001 Spectre"
    ? "Default"
    : T extends "Singularity Spectre"
    ? "Default" | "Blue" | "Red" | "Purple"
    : T extends "Hivemind Spectre"
    ? "Default"
    : T extends "Forsaken Spectre"
    ? "Default" | "Gold"
    : T extends "Velocity Spectre"
    ? "Default" | "Yellow" | "Purple" | "Aquamarine"
    : T extends "Infantry Spectre"
    ? "Default"
    : T extends "Horizon Spectre"
    ? "Default"
    : T extends "Prime Spectre"
    ? "Default" | "Yellow" | "Blue" | "Orange"
    : T extends "Avalanche Spectre"
    ? "Default"
    : T extends "Prism Spectre"
    ? "Default"
    : T extends "Serenity Spectre"
    ? "Default"
    : T extends "Ruination Spectre"
    ? "Default" | "Purple" | "Red/Yellow" | "Green"
    : T extends "Kingdom Spectre"
    ? "Default"
    : T extends "Luxe Spectre"
    ? "Default"
    : T extends "Magepunk Spectre"
    ? "Default" | "Green" | "Purple" | "Orange"
    : T extends "Spline Spectre"
    ? "Default" | "Green" | "Red" | "Blue"
    : T extends "Minima Spectre"
    ? "Default"
    : T extends "Aero Spectre"
    ? "Default" | "Cream/Pink" | "Purple/Gray" | "Green/Black"
    : T extends "POLYfrog Spectre"
    ? "Default"
    : T extends "Protocol 781-A Spectre"
    ? "Default" | "White/Pink" | "Red/Blue" | "Green"
    : T extends "Gravitational Uranium Neuroblaster Spectre"
    ? "Default" | "Chrome" | "Black" | "RWB"
    : T extends "Recon Spectre"
    ? "Default" | "RedCamo" | "BlueCamo" | "GreenCamo"
    : T extends "Infinity Spectre"
    ? "Default" | "White" | "Yellow" | "Pink"
    : T extends "Standard Spectre"
    ? "Default"
    : T extends "Tigris Spectre"
    ? "Default"
    : T extends "Convex Spectre"
    ? "Default"
    : T extends "BlastX Spectre"
    ? "Default" | "Black" | "Yellow" | "Pink"
    : T extends "Wasteland Spectre"
    ? "Default"
    : T extends "RGX 11z Pro Stinger"
    ? "Default" | "Red" | "Blue" | "Yellow"
    : T extends "Aristocrat Stinger"
    ? "Default"
    : T extends "Red Alert Stinger"
    ? "Default"
    : T extends "Surge Stinger"
    ? "Default" | "Black" | "Yellow" | "Blue"
    : T extends "Prism II Stinger"
    ? "Default"
    : T extends "Couture Stinger"
    ? "Default"
    : T extends "Silvanus Stinger"
    ? "Default"
    : T extends "Sensation Stinger"
    ? "Default"
    : T extends "Sakura Stinger"
    ? "Default"
    : T extends "Schema Stinger"
    ? "Default"
    : T extends "Sovereign Stinger"
    ? "Default" | "Gold" | "Silver" | "Purple"
    : T extends "Cavalier Stinger"
    ? "Default"
    : T extends "Standard Stinger"
    ? "Default"
    : T extends "Depths Stinger"
    ? "Default"
    : T extends "Ego Stinger"
    ? "Default" | "Red" | "Tan" | "Pink"
    : T extends "Varnish Stinger"
    ? "Default"
    : T extends "RGX 11z Pro Blade"
    ? "Default" | "Default" | "Default" | "Default"
    : T extends "VALORANT GO! Vol. 1 Knife"
    ? "Default"
    : T extends "Yoru's Stylish Butterfly Comb"
    ? "Default"
    : T extends "Waveform"
    ? "Default" | "Black" | "Red" | "Purple/Pink"
    : T extends "Champions 2021 Karambit"
    ? "Default"
    : T extends "Origin Crescent Blade"
    ? "Default"
    : T extends "Radiant Crisis 001 Baseball Bat"
    ? "Default"
    : T extends "Nebula Knife"
    ? "Default"
    : T extends "Hack"
    ? "Default"
    : T extends "Glitchpop Dagger"
    ? "Default"
    : T extends "Glitchpop Axe"
    ? "Default"
    : T extends "Elderflame Dagger"
    ? "Default"
    : T extends "Singularity Knife"
    ? "Default"
    : T extends "Songsteel"
    ? "Default"
    : T extends "Hivemind Sword"
    ? "Default"
    : T extends "Forsaken Ritual Blade"
    ? "Default"
    : T extends "Velocity Karambit"
    ? "Default" | "Yellow" | "Purple" | "Aquamarine"
    : T extends "Ruin Dagger"
    ? "Default"
    : T extends "Prime Axe"
    ? "Default"
    : T extends "Prime//2.0 Karambit"
    ? "Default"
    : T extends "Outpost Melee"
    ? "Default"
    : T extends "Prism Knife"
    ? "Default"
    : T extends "Prism III Axe"
    ? "Default" | "Pink" | "Green" | "Purple"
    : T extends "Broken Blade of the Ruined King"
    ? "Default" | "Default" | "Default" | "Default"
    : T extends "Kingdom Knife"
    ? "Default"
    : T extends "K/TAC Blade"
    ? "Default"
    : T extends "Smite Knife"
    ? "Default"
    : T extends "Catrina"
    ? "Default" | "Living" | "Eternal"
    : T extends "Celestial Fan"
    ? "Default"
    : T extends "Luxe Knife"
    ? "Default"
    : T extends "Magepunk Electroblade"
    ? "Default" | "Green" | "Purple" | "Orange"
    : T extends "Magepunk Shock Gauntlet"
    ? "Default" | "Default" | "Default" | "Default"
    : T extends "Spline Dagger"
    ? "Default"
    : T extends "Genesis Arc"
    ? "Default"
    : T extends "Ion Energy Sword"
    ? "Default"
    : T extends "Oni Claw"
    ? "Default"
    : T extends "Artisan Foil"
    ? "Default" | "Red" | "Green" | "Blue"
    : T extends "Personal Administrative Melee Unit"
    ? "Default" | "Default" | "Default" | "Default"
    : T extends "Gravitational Uranium Neuroblaster Baton"
    ? "Default"
    : T extends "Snowfall Wand"
    ? "Default"
    : T extends "Relic of the Sentinel"
    ? "Default" | "Default" | "Default" | "Default"
    : T extends "Reaver Knife"
    ? "Default"
    : T extends "Sovereign Sword"
    ? "Default"
    : T extends "Prosperity"
    ? "Default"
    : T extends "Recon Balisong"
    ? "Default" | "RedCamo" | "BlueCamo" | "GreenCamo"
    : T extends "Melee"
    ? "Default"
    : T extends "Hu Else"
    ? "Default"
    : T extends "Ego Knife"
    ? "Default" | "Red" | "Tan" | "Pink"
    : T extends "BlastX Polymer KnifeTech Coated Knife"
    ? "Default" | "Black" | "Yellow" | "Pink"
    : T extends "Winterwunderland Candy Cane"
    ? "Default" | "Green" | "Blue" | "Rainbow"
    : null;
