export type Guns =
    | "Odin"
    | "Ares"
    | "Vandal"
    | "Bulldog"
    | "Phantom"
    | "Judge"
    | "Bucky"
    | "Frenzy"
    | "Classic"
    | "Ghost"
    | "Sheriff"
    | "Shorty"
    | "Operator"
    | "Guardian"
    | "Marshal"
    | "Spectre"
    | "Stinger"
    | "Knife";

export type SkinsType<T> = T extends "Knife"
    ? KnifeSkins
    : T extends "Stinger"
    ? StingerSkins
    : T extends "Spectre"
    ? SpectreSkins
    : T extends "Marshal"
    ? MarshalSkins
    : T extends "Guardian"
    ? GuardianSkins
    : T extends "Operator"
    ? OperatorSkins
    : T extends "Shorty"
    ? ShortySkins
    : T extends "Sheriff"
    ? SheriffSkins
    : T extends "Ghost"
    ? GhostSkins
    : T extends "Classic"
    ? ClassicSkins
    : T extends "Frenzy"
    ? FrenzySkins
    : T extends "Bucky"
    ? BuckySkins
    : T extends "Judge"
    ? JudgeSkins
    : T extends "Phantom"
    ? PhantomSkins
    : T extends "Bulldog"
    ? BulldogSkins
    : T extends "Vandal"
    ? VandalSkins
    : T extends "Ares"
    ? AresSkins
    : T extends "Odin"
    ? OdinSkins
    : null;

export type VandalSkins =
    | "Aristocrat Vandal"
    | "Origin Vandal"
    | "Glitchpop Vandal"
    | "Elderflame Vandal"
    | "Nitro Vandal"
    | "Hivemind Vandal"
    | "Forsaken Vandal"
    | "Ruin Vandal"
    | "dot EXE Vandal"
    | "Horizon Vandal"
    | "Prime Vandal"
    | "Avalanche Vandal"
    | "Prism II Vandal"
    | "K/TAC Vandal"
    | "Luxe Vandal"
    | "Silvanus Vandal"
    | "Sensation Vandal"
    | "Sakura Vandal"
    | "Sentinels of Light Vandal"
    | "Reaver Vandal"
    | "Tethered Realms Vandal"
    | "Cavalier Vandal"
    | "Standard Vandal"
    | "Depths Vandal"
    | "Ego Vandal"
    | "Wasteland Vandal"
    | "Winterwunderland Vandal";

export type OdinSkins =
    | "Glitchpop Odin"
    | "Nitro Odin"
    | "dot EXE Odin"
    | "Prime//2.0 Odin"
    | "Prism III Odin"
    | "Smite Odin"
    | "Sensation Odin"
    | "Lightwave Odin"
    | "Standard Odin"
    | "Aerosol Odin"
    | "BlastX Odin";

export type AresSkins =
    | "Aristocrat Ares"
    | "Nebula Ares"
    | "Singularity Ares"
    | "Rush Ares"
    | "Hivemind Ares"
    | "Infantry Ares"
    | "Outpost Ares"
    | "Prism Ares"
    | "Celestial Ares"
    | "Minima Ares"
    | "POLYfrog Ares"
    | "Jigsaw Ares"
    | "Sakura Ares"
    | "Sentinels of Light Ares"
    | "Standard Ares";

export type BulldogSkins =
    | "Aristocrat Bulldog"
    | "Spectrum Bulldog"
    | "Glitchpop Bulldog"
    | "Rush Bulldog"
    | "Horizon Bulldog"
    | "K/TAC Bulldog"
    | "Couture Bulldog"
    | "POLYfox Bulldog"
    | "Infinity Bulldog"
    | "Standard Bulldog"
    | "Convex Bulldog"
    | "Depths Bulldog"
    | "Varnish Bulldog";

export type PhantomSkins =
    | "VALORANT GO! Vol. 1 Phantom"
    | "Spectrum Phantom"
    | "Nebula Phantom"
    | "Glitchpop Phantom"
    | "Singularity Phantom"
    | "Rush Phantom"
    | "Prime//2.0 Phantom"
    | "Avalanche Phantom"
    | "Prism Phantom"
    | "Serenity Phantom"
    | "Ruination Phantom"
    | "Kingdom Phantom"
    | "Smite Phantom"
    | "Celestial Phantom"
    | "Spline Phantom"
    | "Minima Phantom"
    | "Galleria Phantom"
    | "Silvanus Phantom"
    | "Ion Phantom"
    | "Oni Phantom"
    | "Artisan Phantom"
    | "Lightwave Phantom"
    | "Recon Phantom"
    | "Infinity Phantom"
    | "Standard Phantom"
    | "BlastX Phantom"
    | "Winterwunderland Phantom";

export type JudgeSkins =
    | "Glitchpop Judge"
    | "Elderflame Judge"
    | "Rush Judge"
    | "dot EXE Judge"
    | "Outpost Judge"
    | "Prism III Judge"
    | "Serenity Judge"
    | "Smite Judge"
    | "Celestial Judge"
    | "Luxe Judge"
    | "POLYfox Judge"
    | "Jigsaw Judge"
    | "Sensation Judge"
    | "Standard Judge"
    | "Convex Judge"
    | "Varnish Judge";

export type BuckySkins =
    | "Origin Bucky"
    | "Red Alert Bucky"
    | "Surge Bucky"
    | "Horizon Bucky"
    | "Monarch Bucky"
    | "Prime//2.0 Bucky"
    | "Prism II Bucky"
    | "Kingdom Bucky"
    | "Magepunk Bucky"
    | "Galleria Bucky"
    | "Ion Bucky"
    | "Oni Bucky"
    | "Artisan Bucky"
    | "Gravitational Uranium Neuroblaster Bucky"
    | "Lightwave Bucky"
    | "Cavalier Bucky"
    | "Standard Bucky"
    | "Aerosol Bucky";

export type FrenzySkins =
    | "RagnaRocker Frenzy"
    | "Origin Frenzy"
    | "Glitchpop Frenzy"
    | "Elderflame Frenzy"
    | "Rush Frenzy"
    | "Swooping Frenzy"
    | "Horizon Frenzy"
    | "Monarch Frenzy"
    | "Prime//2.0 Frenzy"
    | "Couture Frenzy"
    | "Celestial Frenzy"
    | "Spitfire Frenzy"
    | "Sensation Frenzy"
    | "Lightwave Frenzy"
    | "Standard Frenzy"
    | "BlastX Frenzy";

export type ClassicSkins =
    | "Spectrum Classic"
    | "Pistolinha Classic"
    | "Red Alert Classic"
    | "Glitchpop Classic"
    | "Surge Classic"
    | "Songsteel Classic"
    | "Forsaken Classic"
    | "FIRE/arm Classic"
    | "Prime Classic"
    | "Avalanche Classic"
    | "Prism III Classic"
    | "Kingdom Classic"
    | "Smite Classic"
    | "Spline Classic"
    | "Galleria Classic"
    | "Gravitational Uranium Neuroblaster Classic"
    | "Sakura Classic"
    | "Infinity Classic"
    | "Standard Classic"
    | "Final Chamber Classic";

export type GhostSkins =
    | "VALORANT GO! Vol. 1 Ghost"
    | "dot EXE Ghost"
    | "Hush Ghost"
    | "Infantry Ghost"
    | "Outpost Ghost"
    | "Prism Ghost"
    | "Serenity Ghost"
    | "Ruination Ghost"
    | "Luxe Ghost"
    | "Magepunk Ghost"
    | "Artisan Ghost"
    | "Jigsaw Ghost"
    | "Eclipse Ghost"
    | "Sovereign Ghost"
    | "Tethered Realms Ghost"
    | "Recon Ghost"
    | "Cavalier Ghost"
    | "Standard Ghost"
    | "Depths Ghost"
    | "Ego Ghost"
    | "Vendetta Ghost"
    | "Winterwunderland Ghost"
    | "Soul Silencer Ghost";

export type SheriffSkins =
    | "Aristocrat Sheriff"
    | "Nebula Sheriff"
    | "Singularity Sheriff"
    | "Surge Sheriff"
    | "Protektor Sheriff"
    | "Prism II Sheriff"
    | "K/TAC Sheriff"
    | "Minima Sheriff"
    | "Silvanus Sheriff"
    | "Ion Sheriff"
    | "POLYfox Sheriff"
    | "POLYfrog Sheriff"
    | "Lightwave Sheriff"
    | "Sakura Sheriff"
    | "Peacekeeper Sheriff"
    | "Sentinels of Light Sheriff"
    | "Reaver Sheriff"
    | "Standard Sheriff"
    | "Convex Sheriff"
    | "Varnish Sheriff"
    | "Wasteland Sheriff"
    | "Game Over Sheriff"
    | "Death Wish Sheriff";

export type ShortySkins =
    | "Hivemind Shorty"
    | "Ruin Shorty"
    | "Monarch Shorty"
    | "Prism II Shorty"
    | "Wunderkind Shorty"
    | "Oni Shorty"
    | "Snakebite Shorty"
    | "Standard Shorty"
    | "Aerosol Shorty"
    | "Wasteland Shorty";

export type OperatorSkins =
    | "Origin Operator"
    | "Red Alert Operator"
    | "Glitchpop Operator"
    | "Elderflame Operator"
    | "Nitro Operator"
    | "Forsaken Operator"
    | "Infantry Operator"
    | "Prism Operator"
    | "K/TAC Operator"
    | "Luxe Operator"
    | "Spline Operator"
    | "Minima Operator"
    | "Silvanus Operator"
    | "Ion Operator"
    | "Gravitational Uranium Neuroblaster Operator"
    | "Sentinels of Light Operator"
    | "Reaver Operator"
    | "Tethered Realms Operator"
    | "Cavalier Operator"
    | "Standard Operator"
    | "Aerosol Operator"
    | "Convex Operator";

export type GuardianSkins =
    | "VALORANT GO! Vol. 1 Guardian"
    | "Spectrum Guardian"
    | "Nebula Guardian"
    | "Nitro Guardian"
    | "Songsteel Guardian"
    | "Ruin Guardian"
    | "Infantry Guardian"
    | "Prime Guardian"
    | "Ruination Guardian"
    | "Galleria Guardian"
    | "Oni Guardian"
    | "POLYfox Guardian"
    | "Jigsaw Guardian"
    | "Reaver Guardian"
    | "Sovereign Guardian"
    | "Tethered Realms Guardian"
    | "Recon Guardian"
    | "Infinity Guardian"
    | "Standard Guardian"
    | "Ego Guardian";

export type MarshalSkins =
    | "Songsteel Marshal"
    | "Ruin Marshal"
    | "Monarch Marshal"
    | "Avalanche Marshal"
    | "Couture Marshal"
    | "Magepunk Marshal"
    | "Galleria Marshal"
    | "POLYfrog Marshal"
    | "Artisan Marshal"
    | "Sovereign Marshal"
    | "Standard Marshal"
    | "Wasteland Marshal"
    | "Winterwunderland Marshal";

export type SpectreSkins =
    | "VALORANT GO! Vol. 1 Spectre"
    | "Singularity Spectre"
    | "Hivemind Spectre"
    | "Forsaken Spectre"
    | "Infantry Spectre"
    | "Horizon Spectre"
    | "Prime Spectre"
    | "Avalanche Spectre"
    | "Prism Spectre"
    | "Serenity Spectre"
    | "Ruination Spectre"
    | "Kingdom Spectre"
    | "Luxe Spectre"
    | "Magepunk Spectre"
    | "Spline Spectre"
    | "Minima Spectre"
    | "POLYfrog Spectre"
    | "Gravitational Uranium Neuroblaster Spectre"
    | "Recon Spectre"
    | "Infinity Spectre"
    | "Standard Spectre"
    | "Convex Spectre"
    | "BlastX Spectre"
    | "Wasteland Spectre";

export type StingerSkins =
    | "Aristocrat Stinger"
    | "Red Alert Stinger"
    | "Surge Stinger"
    | "Prism II Stinger"
    | "Couture Stinger"
    | "Silvanus Stinger"
    | "Sensation Stinger"
    | "Sakura Stinger"
    | "Sovereign Stinger"
    | "Cavalier Stinger"
    | "Standard Stinger"
    | "Depths Stinger"
    | "Ego Stinger"
    | "Varnish Stinger";

export type KnifeSkins =
    | "VALORANT GO! Vol. 1 Knife"
    | "Waveform"
    | "Origin Crescent Blade"
    | "Nebula Knife"
    | "Glitchpop Dagger"
    | "Glitchpop Axe"
    | "Elderflame Dagger"
    | "Singularity Knife"
    | "Songsteel"
    | "Hivemind Sword"
    | "Forsaken Ritual Blade"
    | "Ruin Dagger"
    | "Prime Axe"
    | "Prime//2.0 Karambit"
    | "Outpost Melee"
    | "Prism Knife"
    | "Prism III Axe"
    | "Broken Blade of the Ruined King"
    | "Kingdom Knife"
    | "K/TAC Blade"
    | "Smite Knife"
    | "Celestial Fan"
    | "Luxe Knife"
    | "Magepunk Electroblade"
    | "Spline Dagger"
    | "Ion Energy Sword"
    | "Oni Claw"
    | "Artisan Foil"
    | "Gravitational Uranium Neuroblaster Baton"
    | "Relic of the Sentinel"
    | "Reaver Knife"
    | "Sovereign Sword"
    | "Prosperity"
    | "Recon Balisong"
    | "Ego Knife"
    | "BlastX Polymer KnifeTech Coated Knife"
    | "Winterwunderland Candy Cane";

export type Levels = "Level 1" | "Level 2" | "Level 3" | "Level 4";

export type Variants = "Default" | "Variant 2" | "Variant 3" | "Variant 4";

export type SkinsIdMappedByGunName = {
    [gun in Guns]: Record<SkinsType<gun>, string>;
};

export type VariantSkin<T> = T extends "Aristocrat Ares"
    ? "Default"
    : T extends "Nebula Ares"
    ? "Default"
    : T extends "Singularity Ares"
    ? "Blue" | "Purple" | "Red" | "Default"
    : T extends "Rush Ares"
    ? "Default"
    : T extends "Hivemind Ares"
    ? "Default"
    : T extends "Infantry Ares"
    ? "Default"
    : T extends "Outpost Ares"
    ? "Default"
    : T extends "Prism Ares"
    ? "Default"
    : T extends "Celestial Ares"
    ? "Default"
    : T extends "Minima Ares"
    ? "Default"
    : T extends "POLYfrog Ares"
    ? "Default"
    : T extends "Jigsaw Ares"
    ? "Default" | "Killjoy" | "Astra" | "Yoru"
    : T extends "Sakura Ares"
    ? "Default"
    : T extends "Sentinels of Light Ares"
    ? "Default" | "Pink" | "Red/Green" | "Blue/Purple"
    : T extends "Ares"
    ? "Default"
    : T extends "Origin Bucky"
    ? "Default" | "Green" | "Red" | "White"
    : T extends "Red Alert Bucky"
    ? "Default"
    : T extends "Surge Bucky"
    ? "Default" | "Black" | "Yellow" | "Blue"
    : T extends "Horizon Bucky"
    ? "Default"
    : T extends "Monarch Bucky"
    ? "Default"
    : T extends "Prime//. Bucky"
    ? "Gold" | "Green" | "Orange" | "Default"
    : T extends "Prism II Bucky"
    ? "Default"
    : T extends "Kingdom Bucky"
    ? "Default"
    : T extends "Magepunk Bucky"
    ? "Default" | "Green" | "Purple" | "Orange"
    : T extends "Galleria Bucky"
    ? "Default"
    : T extends "Ion Bucky"
    ? "Default"
    : T extends "Oni Bucky"
    ? "Black" | "Green" | "Default" | "White"
    : T extends "Artisan Bucky"
    ? "Blue" | "Green" | "Red" | "Default"
    : T extends "Gravitational Uranium Neuroblaster Bucky"
    ? "Black" | "Chrome" | "RWB" | "Default"
    : T extends "Lightwave Bucky"
    ? "Default" | "Blue" | "Red" | "Gray"
    : T extends "Cavalier Bucky"
    ? "Default"
    : T extends "Bucky"
    ? "Default"
    : T extends "Aerosol Bucky"
    ? "Default"
    : T extends "Aristocrat Bulldog"
    ? "Default"
    : T extends "Spectrum Bulldog"
    ? "Default" | "Black" | "Red" | "Purple/Pink"
    : T extends "Glitchpop Bulldog"
    ? "Blue" | "Gold" | "Red" | "Default"
    : T extends "Rush Bulldog"
    ? "Default"
    : T extends "Horizon Bulldog"
    ? "Default"
    : T extends "K/TAC Bulldog"
    ? "Default"
    : T extends "Couture Bulldog"
    ? "Default"
    : T extends "POLYfox Bulldog"
    ? "Default"
    : T extends "Infinity Bulldog"
    ? "Default" | "White" | "Yellow" | "Pink"
    : T extends "Bulldog"
    ? "Default"
    : T extends "Convex Bulldog"
    ? "Default"
    : T extends "Depths Bulldog"
    ? "Default"
    : T extends "Spectrum Classic"
    ? "Default" | "Black" | "Red" | "Purple/Pink"
    : T extends "Pistolinha Classic"
    ? "Default"
    : T extends "Red Alert Classic"
    ? "Default"
    : T extends "Glitchpop Classic"
    ? "Blue" | "Gold" | "Red" | "Default"
    : T extends "Surge Classic"
    ? "Default" | "Black" | "Yellow" | "Blue"
    : T extends "Songsteel Classic"
    ? "Default"
    : T extends "Forsaken Classic"
    ? "Default" | "Gold"
    : T extends "Prime Classic"
    ? "Blue" | "Orange" | "Default" | "Yellow"
    : T extends "Avalanche Classic"
    ? "Default"
    : T extends "Prism III Classic"
    ? "Default" | "Pink" | "Green" | "Purple"
    : T extends "Kingdom Classic"
    ? "Default"
    : T extends "Smite Classic"
    ? "Default"
    : T extends "Spline Classic"
    ? "Blue" | "Green" | "Red" | "Default"
    : T extends "Galleria Classic"
    ? "Default"
    : T extends "Gravitational Uranium Neuroblaster Classic"
    ? "Black" | "Chrome" | "RWB" | "Default"
    : T extends "Sakura Classic"
    ? "Default"
    : T extends "Infinity Classic"
    ? "Default" | "White" | "Yellow" | "Pink"
    : T extends "Classic"
    ? "Default"
    : T extends "Final Chamber Classic"
    ? "Default"
    : T extends "RagnaRocker Frenzy"
    ? "Default"
    : T extends "Origin Frenzy"
    ? "Default" | "Green" | "Red" | "White"
    : T extends "Glitchpop Frenzy"
    ? "Blue" | "Gold" | "Red" | "Default"
    : T extends "Elderflame Frenzy"
    ? "Blue" | "Dark" | "Red" | "Default"
    : T extends "Rush Frenzy"
    ? "Default"
    : T extends "Swooping Frenzy"
    ? "Default"
    : T extends "Horizon Frenzy"
    ? "Default"
    : T extends "Monarch Frenzy"
    ? "Default"
    : T extends "Prime//. Frenzy"
    ? "Gold" | "Green" | "Orange" | "Default"
    : T extends "Couture Frenzy"
    ? "Default"
    : T extends "Celestial Frenzy"
    ? "Default"
    : T extends "Spitfire Frenzy"
    ? "Default"
    : T extends "Sensation Frenzy"
    ? "Default"
    : T extends "Lightwave Frenzy"
    ? "Default" | "Blue" | "Red" | "Gray"
    : T extends "Frenzy"
    ? "Default"
    : T extends "BlastX Frenzy"
    ? "Default" | "Black" | "Yellow" | "Pink"
    : T extends "VALORANT GO! Vol.  Ghost"
    ? "Default"
    : T extends "dot EXE Ghost"
    ? "Default"
    : T extends "Hush Ghost"
    ? "Default"
    : T extends "Infantry Ghost"
    ? "Default"
    : T extends "Outpost Ghost"
    ? "Default"
    : T extends "Prism Ghost"
    ? "Default"
    : T extends "Serenity Ghost"
    ? "Default"
    : T extends "Ruination Ghost"
    ? "Default" | "Purple" | "Red/Yellow" | "Green"
    : T extends "Luxe Ghost"
    ? "Default"
    : T extends "Magepunk Ghost"
    ? "Default" | "Green" | "Purple" | "Orange"
    : T extends "Artisan Ghost"
    ? "Blue" | "Green" | "Red" | "Default"
    : T extends "Jigsaw Ghost"
    ? "Default" | "Skye" | "Killjoy" | "Astra"
    : T extends "Eclipse Ghost"
    ? "Default"
    : T extends "Sovereign Ghost"
    ? "Gold" | "Purple" | "Silver" | "Default"
    : T extends "Tethered Realms Ghost"
    ? "Default"
    : T extends "Recon Ghost"
    ? "Default" | "RedCamo" | "BlueCamo" | "GreenCamo"
    : T extends "Cavalier Ghost"
    ? "Default"
    : T extends "Ghost"
    ? "Default"
    : T extends "Depths Ghost"
    ? "Default"
    : T extends "Ego Ghost"
    ? "Default" | "Red" | "Tan" | "Pink"
    : T extends "Vendetta Ghost"
    ? "Default"
    : T extends "Winterwunderland Ghost"
    ? "Default"
    : T extends "Soul Silencer Ghost"
    ? "Default"
    : T extends "VALORANT GO! Vol.  Guardian"
    ? "Default"
    : T extends "Spectrum Guardian"
    ? "Default" | "Black" | "Red" | "Purple/Pink"
    : T extends "Nebula Guardian"
    ? "Default"
    : T extends "Songsteel Guardian"
    ? "Default"
    : T extends "Ruin Guardian"
    ? "Default"
    : T extends "Infantry Guardian"
    ? "Default"
    : T extends "Prime Guardian"
    ? "Blue" | "Orange" | "Default" | "Yellow"
    : T extends "Ruination Guardian"
    ? "Default" | "Purple" | "Red/Yellow" | "Green"
    : T extends "Galleria Guardian"
    ? "Default"
    : T extends "Oni Guardian"
    ? "Black" | "Green" | "Default" | "White"
    : T extends "POLYfox Guardian"
    ? "Default"
    : T extends "Jigsaw Guardian"
    ? "Default" | "Yoru" | "Skye" | "Killjoy"
    : T extends "Reaver Guardian"
    ? "Black" | "Red" | "Default" | "White"
    : T extends "Sovereign Guardian"
    ? "Gold" | "Purple" | "Silver" | "Default"
    : T extends "Tethered Realms Guardian"
    ? "Default"
    : T extends "Recon Guardian"
    ? "Default" | "RedCamo" | "BlueCamo" | "GreenCamo"
    : T extends "Infinity Guardian"
    ? "Default" | "White" | "Yellow" | "Pink"
    : T extends "Guardian"
    ? "Default"
    : T extends "Ego Guardian"
    ? "Default" | "Red" | "Tan" | "Pink"
    : T extends "Glitchpop Judge"
    ? "Blue" | "Gold" | "Red" | "Default"
    : T extends "Elderflame Judge"
    ? "Blue" | "Dark" | "Red" | "Default"
    : T extends "Rush Judge"
    ? "Default"
    : T extends "dot EXE Judge"
    ? "Default"
    : T extends "Outpost Judge"
    ? "Default"
    : T extends "Prism III Judge"
    ? "Default" | "Pink" | "Green" | "Purple"
    : T extends "Serenity Judge"
    ? "Default"
    : T extends "Smite Judge"
    ? "Default"
    : T extends "Celestial Judge"
    ? "Default"
    : T extends "Luxe Judge"
    ? "Default"
    : T extends "POLYfox Judge"
    ? "Default"
    : T extends "Jigsaw Judge"
    ? "Default" | "Astra" | "Yoru" | "Skye"
    : T extends "Sensation Judge"
    ? "Default"
    : T extends "Judge"
    ? "Default"
    : T extends "Convex Judge"
    ? "Default"
    : T extends "VALORANT GO! Vol.  Knife"
    ? "Default"
    : T extends "Waveform"
    ? "Default" | "Black" | "Red" | "Purple/Pink"
    : T extends "Origin Crescent Blade"
    ? "Default"
    : T extends "Nebula Knife"
    ? "Default"
    : T extends "Glitchpop Dagger"
    ? "Default"
    : T extends "Glitchpop Axe"
    ? "Default"
    : T extends "Elderflame Dagger"
    ? "Default"
    : T extends "Singularity Knife"
    ? "Default"
    : T extends "Songsteel"
    ? "Default"
    : T extends "Hivemind Sword"
    ? "Default"
    : T extends "Forsaken Ritual Blade"
    ? "Default"
    : T extends "Ruin Dagger"
    ? "Default"
    : T extends "Prime Axe"
    ? "Default"
    : T extends "Prime//. Karambit"
    ? "Default"
    : T extends "Outpost Melee"
    ? "Default"
    : T extends "Prism Knife"
    ? "Default"
    : T extends "Prism III Axe"
    ? "Default" | "Pink" | "Green" | "Purple"
    : T extends "Blade of the Ruined King"
    ? "Default" | "Purple" | "Red/Yellow" | "Green"
    : T extends "Kingdom Knife"
    ? "Default"
    : T extends "K/TAC Blade"
    ? "Default"
    : T extends "Smite Knife"
    ? "Default"
    : T extends "Celestial Fan"
    ? "Default"
    : T extends "Standard"
    ? "Default"
    : T extends "Magepunk Electroblade"
    ? "Default" | "Green" | "Purple" | "Orange"
    : T extends "Spline Dagger"
    ? "Default"
    : T extends "Ion Energy Sword"
    ? "Default"
    : T extends "Oni Claw"
    ? "Default"
    : T extends "Artisan Foil"
    ? "Blue" | "Green" | "Red" | "Default"
    : T extends "Gravitational Uranium Neuroblaster Baton"
    ? "Default"
    : T extends "Relic of the Sentinel"
    ? "Default" | "Pink" | "Red/Green" | "Blue/Purple"
    : T extends "Reaver Knife"
    ? "Default"
    : T extends "Sovereign Sword"
    ? "Default"
    : T extends "Prosperity"
    ? "Default"
    : T extends "Recon Balisong"
    ? "Default" | "RedCamo" | "BlueCamo" | "GreenCamo"
    : T extends "Standard Melee"
    ? "Default"
    : T extends "Ego Knife"
    ? "Default" | "Red" | "Tan" | "Pink"
    : T extends "BlastX Polymer KnifeTech Coated Knife"
    ? "Default" | "Black" | "Yellow" | "Pink"
    : T extends "Winterwunderland Candy Cane"
    ? "Default" | "Green" | "Blue" | "Rainbow"
    : T extends "Songsteel Marshal"
    ? "Default"
    : T extends "Ruin Marshal"
    ? "Default"
    : T extends "Monarch Marshal"
    ? "Default"
    : T extends "Avalanche Marshal"
    ? "Default"
    : T extends "Couture Marshal"
    ? "Default"
    : T extends "Magepunk Marshal"
    ? "Default" | "Green" | "Purple" | "Orange"
    : T extends "POLYfrog Marshal"
    ? "Default"
    : T extends "Artisan Marshal"
    ? "Blue" | "Green" | "Red" | "Default"
    : T extends "Sovereign Marshal"
    ? "Gold" | "Purple" | "Silver" | "Default"
    : T extends "Marshal"
    ? "Default"
    : T extends "Wasteland Marshal"
    ? "Default"
    : T extends "Winterwunderland Marshal"
    ? "Default"
    : T extends "Glitchpop Odin"
    ? "Blue" | "Gold" | "Red" | "Default"
    : T extends "dot EXE Odin"
    ? "Default"
    : T extends "Prime//. Odin"
    ? "Gold" | "Green" | "Orange" | "Default"
    : T extends "Prism III Odin"
    ? "Default" | "Pink" | "Green" | "Purple"
    : T extends "Smite Odin"
    ? "Default"
    : T extends "Sensation Odin"
    ? "Default"
    : T extends "Lightwave Odin"
    ? "Default" | "Blue" | "Red" | "Gray"
    : T extends "Odin"
    ? "Default"
    : T extends "Aerosol Odin"
    ? "Default"
    : T extends "BlastX Odin"
    ? "Default" | "Black" | "Yellow" | "Pink"
    : T extends "Origin Operator"
    ? "Default" | "Green" | "Red" | "White"
    : T extends "Red Alert Operator"
    ? "Default"
    : T extends "Glitchpop Operator"
    ? "Blue" | "Gold" | "Red" | "Default"
    : T extends "Elderflame Operator"
    ? "Blue" | "Dark" | "Red" | "Default"
    : T extends "Forsaken Operator"
    ? "Default" | "Gold"
    : T extends "Infantry Operator"
    ? "Default"
    : T extends "Prism Operator"
    ? "Default"
    : T extends "K/TAC Operator"
    ? "Default"
    : T extends "Luxe Operator"
    ? "Default"
    : T extends "Spline Operator"
    ? "Blue" | "Green" | "Red" | "Default"
    : T extends "Minima Operator"
    ? "Default"
    : T extends "Silvanus Operator"
    ? "Default"
    : T extends "Ion Operator"
    ? "Default"
    : T extends "Gravitational Uranium Neuroblaster Operator"
    ? "Black" | "Chrome" | "RWB" | "Default"
    : T extends "Sentinels of Light Operator"
    ? "Default" | "Pink" | "Red/Green" | "Blue/Purple"
    : T extends "Reaver Operator"
    ? "Black" | "Red" | "Default" | "White"
    : T extends "Tethered Realms Operator"
    ? "Default"
    : T extends "Cavalier Operator"
    ? "Default"
    : T extends "Operator"
    ? "Default"
    : T extends "Aerosol Operator"
    ? "Default"
    : T extends "Convex Operator"
    ? "Default"
    : T extends "VALORANT GO! Vol.  Phantom"
    ? "Default"
    : T extends "Spectrum Phantom"
    ? "Default" | "Black" | "Red" | "Purple/Pink"
    : T extends "Nebula Phantom"
    ? "Default"
    : T extends "Glitchpop Phantom"
    ? "Blue" | "Gold" | "Red" | "Default"
    : T extends "Singularity Phantom"
    ? "Blue" | "Purple" | "Red" | "Default"
    : T extends "Rush Phantom"
    ? "Default"
    : T extends "Prime//. Phantom"
    ? "Gold" | "Green" | "Orange" | "Default"
    : T extends "Avalanche Phantom"
    ? "Default"
    : T extends "Prism Phantom"
    ? "Default"
    : T extends "Serenity Phantom"
    ? "Default"
    : T extends "Ruination Phantom"
    ? "Default" | "Purple" | "Red/Yellow" | "Green"
    : T extends "Kingdom Phantom"
    ? "Default"
    : T extends "Smite Phantom"
    ? "Default"
    : T extends "Celestial Phantom"
    ? "Default"
    : T extends "Spline Phantom"
    ? "Blue" | "Green" | "Red" | "Default"
    : T extends "Minima Phantom"
    ? "Default"
    : T extends "Galleria Phantom"
    ? "Default"
    : T extends "Silvanus Phantom"
    ? "Default"
    : T extends "Ion Phantom"
    ? "Default"
    : T extends "Oni Phantom"
    ? "Black" | "Green" | "Default" | "White"
    : T extends "Artisan Phantom"
    ? "Blue" | "Green" | "Red" | "Default"
    : T extends "Lightwave Phantom"
    ? "Default" | "Blue" | "Red" | "Gray"
    : T extends "Recon Phantom"
    ? "Default" | "RedCamo" | "BlueCamo" | "GreenCamo"
    : T extends "Infinity Phantom"
    ? "Default" | "White" | "Yellow" | "Pink"
    : T extends "Phantom"
    ? "Default"
    : T extends "BlastX Phantom"
    ? "Default" | "Black" | "Yellow" | "Pink"
    : T extends "Winterwunderland Phantom"
    ? "Default"
    : T extends "Aristocrat Sheriff"
    ? "Default"
    : T extends "Nebula Sheriff"
    ? "Default"
    : T extends "Singularity Sheriff"
    ? "Blue" | "Purple" | "Red" | "Default"
    : T extends "Surge Sheriff"
    ? "Default" | "Black" | "Yellow" | "Blue"
    : T extends "Protektor Sheriff"
    ? "Default"
    : T extends "Prism II Sheriff"
    ? "Default"
    : T extends "K/TAC Sheriff"
    ? "Default"
    : T extends "Minima Sheriff"
    ? "Default"
    : T extends "Silvanus Sheriff"
    ? "Default"
    : T extends "Ion Sheriff"
    ? "Default"
    : T extends "POLYfox Sheriff"
    ? "Default"
    : T extends "POLYfrog Sheriff"
    ? "Default"
    : T extends "Lightwave Sheriff"
    ? "Default" | "Blue" | "Red" | "Gray"
    : T extends "Sakura Sheriff"
    ? "Default"
    : T extends "Peacekeeper Sheriff"
    ? "Default"
    : T extends "Sentinels of Light Sheriff"
    ? "Default" | "Pink" | "Red/Green" | "Blue/Purple"
    : T extends "Reaver Sheriff"
    ? "Black" | "Red" | "Default" | "White"
    : T extends "Sheriff"
    ? "Default"
    : T extends "Convex Sheriff"
    ? "Default"
    : T extends "Wasteland Sheriff"
    ? "Default"
    : T extends "Game Over Sheriff"
    ? "Default"
    : T extends "Death Wish Sheriff"
    ? "Default"
    : T extends "Hivemind Shorty"
    ? "Default"
    : T extends "Ruin Shorty"
    ? "Default"
    : T extends "Monarch Shorty"
    ? "Default"
    : T extends "Prism II Shorty"
    ? "Default"
    : T extends "Wunderkind Shorty"
    ? "Default"
    : T extends "Oni Shorty"
    ? "Black" | "Green" | "Default" | "White"
    : T extends "Snakebite Shorty"
    ? "Default"
    : T extends "Shorty"
    ? "Default"
    : T extends "Aerosol Shorty"
    ? "Default"
    : T extends "Wasteland Shorty"
    ? "Default"
    : T extends "VALORANT GO! Vol.  Spectre"
    ? "Default"
    : T extends "Singularity Spectre"
    ? "Blue" | "Purple" | "Red" | "Default"
    : T extends "Hivemind Spectre"
    ? "Default"
    : T extends "Forsaken Spectre"
    ? "Default" | "Gold"
    : T extends "Infantry Spectre"
    ? "Default"
    : T extends "Horizon Spectre"
    ? "Default"
    : T extends "Prime Spectre"
    ? "Blue" | "Orange" | "Default" | "Yellow"
    : T extends "Avalanche Spectre"
    ? "Default"
    : T extends "Prism Spectre"
    ? "Default"
    : T extends "Serenity Spectre"
    ? "Default"
    : T extends "Ruination Spectre"
    ? "Default" | "Purple" | "Red/Yellow" | "Green"
    : T extends "Kingdom Spectre"
    ? "Default"
    : T extends "Luxe Spectre"
    ? "Default"
    : T extends "Magepunk Spectre"
    ? "Default" | "Green" | "Purple" | "Orange"
    : T extends "Spline Spectre"
    ? "Blue" | "Green" | "Red" | "Default"
    : T extends "Minima Spectre"
    ? "Default"
    : T extends "POLYfrog Spectre"
    ? "Default"
    : T extends "Gravitational Uranium Neuroblaster Spectre"
    ? "Black" | "Chrome" | "RWB" | "Default"
    : T extends "Recon Spectre"
    ? "Default" | "RedCamo" | "BlueCamo" | "GreenCamo"
    : T extends "Infinity Spectre"
    ? "Default" | "White" | "Yellow" | "Pink"
    : T extends "Spectre"
    ? "Default"
    : T extends "Convex Spectre"
    ? "Default"
    : T extends "BlastX Spectre"
    ? "Default" | "Black" | "Yellow" | "Pink"
    : T extends "Wasteland Spectre"
    ? "Default"
    : T extends "Aristocrat Stinger"
    ? "Default"
    : T extends "Red Alert Stinger"
    ? "Default"
    : T extends "Surge Stinger"
    ? "Default" | "Black" | "Yellow" | "Blue"
    : T extends "Prism II Stinger"
    ? "Default"
    : T extends "Couture Stinger"
    ? "Default"
    : T extends "Silvanus Stinger"
    ? "Default"
    : T extends "Sensation Stinger"
    ? "Default"
    : T extends "Sakura Stinger"
    ? "Default"
    : T extends "Sovereign Stinger"
    ? "Gold" | "Purple" | "Silver" | "Default"
    : T extends "Cavalier Stinger"
    ? "Default"
    : T extends "Stinger"
    ? "Default"
    : T extends "Depths Stinger"
    ? "Default"
    : T extends "Ego Stinger"
    ? "Default" | "Red" | "Tan" | "Pink"
    : T extends "Aristocrat Vandal"
    ? "Default"
    : T extends "Origin Vandal"
    ? "Default" | "Green" | "Red" | "White"
    : T extends "Glitchpop Vandal"
    ? "Blue" | "Gold" | "Red" | "Default"
    : T extends "Elderflame Vandal"
    ? "Blue" | "Dark" | "Red" | "Default"
    : T extends "Hivemind Vandal"
    ? "Default"
    : T extends "Forsaken Vandal"
    ? "Default" | "Gold"
    : T extends "Ruin Vandal"
    ? "Default"
    : T extends "dot EXE Vandal"
    ? "Default"
    : T extends "Horizon Vandal"
    ? "Default"
    : T extends "Prime Vandal"
    ? "Blue" | "Orange" | "Default" | "Yellow"
    : T extends "Avalanche Vandal"
    ? "Default"
    : T extends "Prism II Vandal"
    ? "Default"
    : T extends "K/TAC Vandal"
    ? "Default"
    : T extends "Luxe Vandal"
    ? "Default"
    : T extends "Silvanus Vandal"
    ? "Default"
    : T extends "Sensation Vandal"
    ? "Default"
    : T extends "Sakura Vandal"
    ? "Default"
    : T extends "Sentinels of Light Vandal"
    ? "Default" | "Pink" | "Red/Green" | "Blue/Purple"
    : T extends "Reaver Vandal"
    ? "Black" | "Red" | "Default" | "White"
    : T extends "Tethered Realms Vandal"
    ? "Default"
    : T extends "Cavalier Vandal"
    ? "Default"
    : T extends "Vandal"
    ? "Default"
    : T extends "Depths Vandal"
    ? "Default"
    : T extends "Ego Vandal"
    ? "Default" | "Red" | "Tan" | "Pink"
    : T extends "Wasteland Vandal"
    ? "Default"
    : T extends "Winterwunderland Vandal"
    ? "Default"
    : "Default";
