/* FILE GENERATED AUTOMATICALLY */

export type OdinSkin =
    | "Glitchpop Odin"
    | "Nitro Odin"
    | "dot EXE Odin"
    | "Prime//2.0 Odin"
    | "Prism III Odin"
    | "Smite Odin"
    | "Sensation Odin"
    | "Lightwave Odin"
    | "Standard Odin"
    | "Aerosol Odin"
    | "BlastX Odin";

export type AresSkin =
    | "VALORANT GO! Vol. 2 Ares"
    | "Aristocrat Ares"
    | "Nebula Ares"
    | "Singularity Ares"
    | "Rush Ares"
    | "Hivemind Ares"
    | "Infantry Ares"
    | "Outpost Ares"
    | "Prism Ares"
    | "Celestial Ares"
    | "Minima Ares"
    | "POLYfrog Ares"
    | "Jigsaw Ares"
    | "Sakura Ares"
    | "Sentinels of Light Ares"
    | "Standard Ares";

export type VandalSkin =
    | "VALORANT GO! Vol. 2 Vandal"
    | "Aristocrat Vandal"
    | "Origin Vandal"
    | "Glitchpop Vandal"
    | "Elderflame Vandal"
    | "Nitro Vandal"
    | "Hivemind Vandal"
    | "Forsaken Vandal"
    | "Ruin Vandal"
    | "dot EXE Vandal"
    | "Horizon Vandal"
    | "Prime Vandal"
    | "Avalanche Vandal"
    | "Prism II Vandal"
    | "K/TAC Vandal"
    | "Luxe Vandal"
    | "Silvanus Vandal"
    | "Sensation Vandal"
    | "Sakura Vandal"
    | "Sentinels of Light Vandal"
    | "Reaver Vandal"
    | "Tethered Realms Vandal"
    | "Cavalier Vandal"
    | "Standard Vandal"
    | "Depths Vandal"
    | "Ego Vandal"
    | "Wasteland Vandal"
    | "Winterwunderland Vandal";

export type BulldogSkin =
    | "Aristocrat Bulldog"
    | "Spectrum Bulldog"
    | "Glitchpop Bulldog"
    | "Rush Bulldog"
    | "Horizon Bulldog"
    | "K/TAC Bulldog"
    | "Couture Bulldog"
    | "POLYfox Bulldog"
    | "Infinity Bulldog"
    | "Standard Bulldog"
    | "Convex Bulldog"
    | "Depths Bulldog"
    | "Varnish Bulldog";

export type PhantomSkin =
    | "VALORANT GO! Vol. 1 Phantom"
    | "Spectrum Phantom"
    | "Nebula Phantom"
    | "Glitchpop Phantom"
    | "Singularity Phantom"
    | "Rush Phantom"
    | "Prime//2.0 Phantom"
    | "Avalanche Phantom"
    | "Prism Phantom"
    | "Serenity Phantom"
    | "Ruination Phantom"
    | "Kingdom Phantom"
    | "Smite Phantom"
    | "Celestial Phantom"
    | "Spline Phantom"
    | "Minima Phantom"
    | "Galleria Phantom"
    | "Silvanus Phantom"
    | "Ion Phantom"
    | "Oni Phantom"
    | "Artisan Phantom"
    | "Lightwave Phantom"
    | "Recon Phantom"
    | "Infinity Phantom"
    | "Standard Phantom"
    | "BlastX Phantom"
    | "Winterwunderland Phantom";

export type JudgeSkin =
    | "Glitchpop Judge"
    | "Elderflame Judge"
    | "Rush Judge"
    | "dot EXE Judge"
    | "Outpost Judge"
    | "Prism III Judge"
    | "Serenity Judge"
    | "Smite Judge"
    | "Celestial Judge"
    | "Luxe Judge"
    | "POLYfox Judge"
    | "Jigsaw Judge"
    | "Sensation Judge"
    | "Standard Judge"
    | "Convex Judge"
    | "Varnish Judge";

export type BuckySkin =
    | "Origin Bucky"
    | "Red Alert Bucky"
    | "Surge Bucky"
    | "Horizon Bucky"
    | "Monarch Bucky"
    | "Prime//2.0 Bucky"
    | "Prism II Bucky"
    | "Kingdom Bucky"
    | "Magepunk Bucky"
    | "Galleria Bucky"
    | "Ion Bucky"
    | "Oni Bucky"
    | "Artisan Bucky"
    | "Gravitational Uranium Neuroblaster Bucky"
    | "Lightwave Bucky"
    | "Cavalier Bucky"
    | "Standard Bucky"
    | "Aerosol Bucky";

export type FrenzySkin =
    | "RagnaRocker Frenzy"
    | "Origin Frenzy"
    | "Glitchpop Frenzy"
    | "Elderflame Frenzy"
    | "Rush Frenzy"
    | "Swooping Frenzy"
    | "Horizon Frenzy"
    | "Monarch Frenzy"
    | "Prime//2.0 Frenzy"
    | "Couture Frenzy"
    | "Celestial Frenzy"
    | "Spitfire Frenzy"
    | "Sensation Frenzy"
    | "Lightwave Frenzy"
    | "Standard Frenzy"
    | "BlastX Frenzy";

export type ClassicSkin =
    | "VALORANT GO! Vol. 2 Classic"
    | "Spectrum Classic"
    | "Pistolinha Classic"
    | "Red Alert Classic"
    | "Glitchpop Classic"
    | "Surge Classic"
    | "Songsteel Classic"
    | "Forsaken Classic"
    | "FIRE/arm Classic"
    | "Prime Classic"
    | "Avalanche Classic"
    | "Prism III Classic"
    | "Kingdom Classic"
    | "Smite Classic"
    | "Spline Classic"
    | "Galleria Classic"
    | "Gravitational Uranium Neuroblaster Classic"
    | "Sakura Classic"
    | "Infinity Classic"
    | "Standard Classic"
    | "Final Chamber Classic";

export type GhostSkin =
    | "VALORANT GO! Vol. 1 Ghost"
    | "dot EXE Ghost"
    | "Hush Ghost"
    | "Infantry Ghost"
    | "Outpost Ghost"
    | "Prism Ghost"
    | "Serenity Ghost"
    | "Ruination Ghost"
    | "Luxe Ghost"
    | "Magepunk Ghost"
    | "Artisan Ghost"
    | "Jigsaw Ghost"
    | "Eclipse Ghost"
    | "Sovereign Ghost"
    | "Tethered Realms Ghost"
    | "Recon Ghost"
    | "Cavalier Ghost"
    | "Standard Ghost"
    | "Depths Ghost"
    | "Ego Ghost"
    | "Vendetta Ghost"
    | "Winterwunderland Ghost"
    | "Soul Silencer Ghost";

export type SheriffSkin =
    | "Aristocrat Sheriff"
    | "Nebula Sheriff"
    | "Singularity Sheriff"
    | "Surge Sheriff"
    | "Protektor Sheriff"
    | "Prism II Sheriff"
    | "K/TAC Sheriff"
    | "Minima Sheriff"
    | "Silvanus Sheriff"
    | "Ion Sheriff"
    | "POLYfox Sheriff"
    | "POLYfrog Sheriff"
    | "Lightwave Sheriff"
    | "Sakura Sheriff"
    | "Peacekeeper Sheriff"
    | "Sentinels of Light Sheriff"
    | "Reaver Sheriff"
    | "Standard Sheriff"
    | "Convex Sheriff"
    | "Varnish Sheriff"
    | "Wasteland Sheriff"
    | "Game Over Sheriff"
    | "Death Wish Sheriff";

export type ShortySkin =
    | "Hivemind Shorty"
    | "Ruin Shorty"
    | "Monarch Shorty"
    | "Prism II Shorty"
    | "Wunderkind Shorty"
    | "Oni Shorty"
    | "Snakebite Shorty"
    | "Standard Shorty"
    | "Aerosol Shorty"
    | "Wasteland Shorty";

export type OperatorSkin =
    | "VALORANT GO! Vol. 2 Operator"
    | "Origin Operator"
    | "Red Alert Operator"
    | "Glitchpop Operator"
    | "Elderflame Operator"
    | "Nitro Operator"
    | "Forsaken Operator"
    | "Infantry Operator"
    | "Prism Operator"
    | "K/TAC Operator"
    | "Luxe Operator"
    | "Spline Operator"
    | "Minima Operator"
    | "Silvanus Operator"
    | "Ion Operator"
    | "Gravitational Uranium Neuroblaster Operator"
    | "Sentinels of Light Operator"
    | "Reaver Operator"
    | "Tethered Realms Operator"
    | "Cavalier Operator"
    | "Standard Operator"
    | "Aerosol Operator"
    | "Convex Operator";

export type GuardianSkin =
    | "VALORANT GO! Vol. 1 Guardian"
    | "Spectrum Guardian"
    | "Nebula Guardian"
    | "Nitro Guardian"
    | "Songsteel Guardian"
    | "Ruin Guardian"
    | "Infantry Guardian"
    | "Prime Guardian"
    | "Ruination Guardian"
    | "Galleria Guardian"
    | "Oni Guardian"
    | "POLYfox Guardian"
    | "Jigsaw Guardian"
    | "Reaver Guardian"
    | "Sovereign Guardian"
    | "Tethered Realms Guardian"
    | "Recon Guardian"
    | "Infinity Guardian"
    | "Standard Guardian"
    | "Ego Guardian";

export type MarshalSkin =
    | "Songsteel Marshal"
    | "Ruin Marshal"
    | "Monarch Marshal"
    | "Avalanche Marshal"
    | "Couture Marshal"
    | "Magepunk Marshal"
    | "Galleria Marshal"
    | "POLYfrog Marshal"
    | "Artisan Marshal"
    | "Sovereign Marshal"
    | "Standard Marshal"
    | "Wasteland Marshal"
    | "Winterwunderland Marshal";

export type SpectreSkin =
    | "VALORANT GO! Vol. 1 Spectre"
    | "Singularity Spectre"
    | "Hivemind Spectre"
    | "Forsaken Spectre"
    | "Infantry Spectre"
    | "Horizon Spectre"
    | "Prime Spectre"
    | "Avalanche Spectre"
    | "Prism Spectre"
    | "Serenity Spectre"
    | "Ruination Spectre"
    | "Kingdom Spectre"
    | "Luxe Spectre"
    | "Magepunk Spectre"
    | "Spline Spectre"
    | "Minima Spectre"
    | "POLYfrog Spectre"
    | "Gravitational Uranium Neuroblaster Spectre"
    | "Recon Spectre"
    | "Infinity Spectre"
    | "Standard Spectre"
    | "Convex Spectre"
    | "BlastX Spectre"
    | "Wasteland Spectre";

export type StingerSkin =
    | "Aristocrat Stinger"
    | "Red Alert Stinger"
    | "Surge Stinger"
    | "Prism II Stinger"
    | "Couture Stinger"
    | "Silvanus Stinger"
    | "Sensation Stinger"
    | "Sakura Stinger"
    | "Sovereign Stinger"
    | "Cavalier Stinger"
    | "Standard Stinger"
    | "Depths Stinger"
    | "Ego Stinger"
    | "Varnish Stinger";

export type KnifeSkin =
    | "VALORANT GO! Vol. 1 Knife"
    | "Yoru's Stylish Butterfly Comb"
    | "Waveform"
    | "Origin Crescent Blade"
    | "Nebula Knife"
    | "Glitchpop Dagger"
    | "Glitchpop Axe"
    | "Elderflame Dagger"
    | "Singularity Knife"
    | "Songsteel"
    | "Hivemind Sword"
    | "Forsaken Ritual Blade"
    | "Ruin Dagger"
    | "Prime Axe"
    | "Prime//2.0 Karambit"
    | "Outpost Melee"
    | "Prism Knife"
    | "Prism III Axe"
    | "Broken Blade of the Ruined King"
    | "Kingdom Knife"
    | "K/TAC Blade"
    | "Smite Knife"
    | "Celestial Fan"
    | "Luxe Knife"
    | "Magepunk Electroblade"
    | "Spline Dagger"
    | "Ion Energy Sword"
    | "Oni Claw"
    | "Artisan Foil"
    | "Gravitational Uranium Neuroblaster Baton"
    | "Relic of the Sentinel"
    | "Reaver Knife"
    | "Sovereign Sword"
    | "Prosperity"
    | "Recon Balisong"
    | "Melee"
    | "Ego Knife"
    | "BlastX Polymer KnifeTech Coated Knife"
    | "Winterwunderland Candy Cane";
