/* FILE GENERATED AUTOMATICALLY */

export type OdinSkin =
    | "Glitchpop Odin"
    | "Nitro Odin"
    | "dot EXE Odin"
    | "Prime//2.0 Odin"
    | "Prism III Odin"
    | "Smite Odin"
    | "Coalition: Cobra Odin"
    | "Sensation Odin"
    | "Lightwave Odin"
    | "Schema Odin"
    | "Lycan's Bane Odin"
    | "Standard Odin"
    | "Aerosol Odin"
    | "BlastX Odin";

export type AresSkin =
    | "VALORANT GO! Vol. 2 Ares"
    | "Aristocrat Ares"
    | "Endeavour Ares"
    | "Nebula Ares"
    | "Doodle Buds Ares"
    | "Singularity Ares"
    | "Rush Ares"
    | "Hivemind Ares"
    | "Infantry Ares"
    | "Goldwing Ares"
    | "Outpost Ares"
    | "Prism Ares"
    | "Nunca Olvidados Ares"
    | "Celestial Ares"
    | "Magepunk Ares"
    | "Minima Ares"
    | "POLYfrog Ares"
    | "Divine Swine Ares"
    | "Jigsaw Ares"
    | "Sakura Ares"
    | "Snowfall Ares"
    | "Sentinels of Light Ares"
    | "Titanmail Ares"
    | "Standard Ares";

export type VandalSkin =
    | "RGX 11z Pro Vandal"
    | "VALORANT GO! Vol. 2 Vandal"
    | "Neptune Vandal"
    | "Aristocrat Vandal"
    | "Gaia's Vengeance Vandal"
    | "Endeavour Vandal"
    | "Champions 2021 Vandal"
    | "Origin Vandal"
    | "Glitchpop Vandal"
    | "Elderflame Vandal"
    | "Nitro Vandal"
    | "Hivemind Vandal"
    | "Forsaken Vandal"
    | "Team Ace Vandal"
    | "Ruin Vandal"
    | "dot EXE Vandal"
    | ".SYS Vandal"
    | "Horizon Vandal"
    | "Prime Vandal"
    | "Avalanche Vandal"
    | "Prism II Vandal"
    | "K/TAC Vandal"
    | "Nunca Olvidados Vandal"
    | "Luxe Vandal"
    | "Silvanus Vandal"
    | "Sensation Vandal"
    | "Sakura Vandal"
    | "Schema Vandal"
    | "Lycan's Bane Vandal"
    | "Sentinels of Light Vandal"
    | "Reaver Vandal"
    | "Tethered Realms Vandal"
    | "Cavalier Vandal"
    | "Titanmail Vandal"
    | "Standard Vandal"
    | "Depths Vandal"
    | "Ego Vandal"
    | "Wasteland Vandal"
    | "Winterwunderland Vandal";

export type BulldogSkin =
    | "Aristocrat Bulldog"
    | "Endeavour Bulldog"
    | "Spectrum Bulldog"
    | "Striker Bulldog"
    | "Undercity Bulldog"
    | "Glitchpop Bulldog"
    | "Rush Bulldog"
    | "Velocity Bulldog"
    | "Horizon Bulldog"
    | "K/TAC Bulldog"
    | "Couture Bulldog"
    | "Nunca Olvidados Bulldog"
    | "Genesis Bulldog"
    | "Hue Shift Bulldog"
    | "POLYfox Bulldog"
    | "Protocol 781-A Bulldog"
    | "Infinity Bulldog"
    | "Standard Bulldog"
    | "Convex Bulldog"
    | "Depths Bulldog"
    | "Varnish Bulldog";

export type PhantomSkin =
    | "RGX 11z Pro Phantom"
    | "VALORANT GO! Vol. 1 Phantom"
    | "Spectrum Phantom"
    | "Radiant Crisis 001 Phantom"
    | "Nebula Phantom"
    | "Undercity Phantom"
    | "Glitchpop Phantom"
    | "Doodle Buds Phantom"
    | "Singularity Phantom"
    | "Rush Phantom"
    | "Velocity Phantom"
    | "Team Ace Phantom"
    | "Prime//2.0 Phantom"
    | "Avalanche Phantom"
    | "Prism Phantom"
    | "Serenity Phantom"
    | "Ruination Phantom"
    | "Kingdom Phantom"
    | "Smite Phantom"
    | "Celestial Phantom"
    | "Spline Phantom"
    | "Minima Phantom"
    | "Galleria Phantom"
    | "Silvanus Phantom"
    | "Ion Phantom"
    | "Oni Phantom"
    | "Hue Shift Phantom"
    | "Aero Phantom"
    | "Artisan Phantom"
    | "Protocol 781-A Phantom"
    | "Lightwave Phantom"
    | "Snowfall Phantom"
    | "Recon Phantom"
    | "Infinity Phantom"
    | "Standard Phantom"
    | "Tigris Phantom"
    | "BlastX Phantom"
    | "Winterwunderland Phantom";

export type JudgeSkin =
    | "Undercity Judge"
    | "Glitchpop Judge"
    | "Elderflame Judge"
    | "Rush Judge"
    | "Team Ace Judge"
    | "dot EXE Judge"
    | "Goldwing Judge"
    | "Hydrodip Judge"
    | "Outpost Judge"
    | "Prism III Judge"
    | "Serenity Judge"
    | "Smite Judge"
    | "Celestial Judge"
    | "Luxe Judge"
    | "Coalition: Cobra Judge"
    | "POLYfox Judge"
    | "Divine Swine Judge"
    | "Jigsaw Judge"
    | "Sensation Judge"
    | "Snowfall Judge"
    | "Standard Judge"
    | "Convex Judge"
    | "Varnish Judge";

export type BuckySkin =
    | "Origin Bucky"
    | "Radiant Crisis 001 Bucky"
    | "Red Alert Bucky"
    | "Surge Bucky"
    | ".SYS Bucky"
    | "Horizon Bucky"
    | "Monarch Bucky"
    | "Hydrodip Bucky"
    | "Prime//2.0 Bucky"
    | "Prism II Bucky"
    | "Kingdom Bucky"
    | "Magepunk Bucky"
    | "Galleria Bucky"
    | "Genesis Bucky"
    | "Ion Bucky"
    | "Oni Bucky"
    | "Artisan Bucky"
    | "Gravitational Uranium Neuroblaster Bucky"
    | "Lightwave Bucky"
    | "Cavalier Bucky"
    | "Titanmail Bucky"
    | "Standard Bucky"
    | "Aerosol Bucky";

export type FrenzySkin =
    | "RGX 11z Pro Frenzy"
    | "RagnaRocker Frenzy"
    | "Origin Frenzy"
    | "Glitchpop Frenzy"
    | "Elderflame Frenzy"
    | "Rush Frenzy"
    | "Team Ace Frenzy"
    | "Swooping Frenzy"
    | "Horizon Frenzy"
    | "Monarch Frenzy"
    | "Hydrodip Frenzy"
    | "Prime//2.0 Frenzy"
    | "Couture Frenzy"
    | "Nunca Olvidados Frenzy"
    | "Celestial Frenzy"
    | "Coalition: Cobra Frenzy"
    | "Spitfire Frenzy"
    | "Aero Frenzy"
    | "Divine Swine Frenzy"
    | "Sensation Frenzy"
    | "Lightwave Frenzy"
    | "Titanmail Frenzy"
    | "Live Wire Frenzy"
    | "Standard Frenzy"
    | "BlastX Frenzy";

export type ClassicSkin =
    | "RGX 11z Pro Classic"
    | "VALORANT GO! Vol. 2 Classic"
    | "Spectrum Classic"
    | "Pistolinha Classic"
    | "Striker Classic"
    | "Radiant Crisis 001 Classic"
    | "Red Alert Classic"
    | "Undercity Classic"
    | "Glitchpop Classic"
    | "Finesse Classic"
    | "Surge Classic"
    | "Songsteel Classic"
    | "Forsaken Classic"
    | "FIRE/arm Classic"
    | "Goldwing Classic"
    | "Prime Classic"
    | "Avalanche Classic"
    | "Prism III Classic"
    | "Kingdom Classic"
    | "Smite Classic"
    | "Spline Classic"
    | "Galleria Classic"
    | "Gravitational Uranium Neuroblaster Classic"
    | "Sakura Classic"
    | "Snowfall Classic"
    | "Infinity Classic"
    | "Standard Classic"
    | "Final Chamber Classic";

export type GhostSkin =
    | "VALORANT GO! Vol. 1 Ghost"
    | "Gaia's Vengeance Ghost"
    | "Endeavour Ghost"
    | "dot EXE Ghost"
    | "Hush Ghost"
    | "Infantry Ghost"
    | "Goldwing Ghost"
    | "Outpost Ghost"
    | "Prism Ghost"
    | "Serenity Ghost"
    | "Ruination Ghost"
    | "Luxe Ghost"
    | "Magepunk Ghost"
    | "Artisan Ghost"
    | "Jigsaw Ghost"
    | "Eclipse Ghost"
    | "Lycan's Bane Ghost"
    | "Sovereign Ghost"
    | "Tethered Realms Ghost"
    | "Recon Ghost"
    | "Cavalier Ghost"
    | "Standard Ghost"
    | "Depths Ghost"
    | "Ego Ghost"
    | "Vendetta Ghost"
    | "Winterwunderland Ghost"
    | "Soul Silencer Ghost";

export type SheriffSkin =
    | "Aristocrat Sheriff"
    | "Nebula Sheriff"
    | "Singularity Sheriff"
    | "Surge Sheriff"
    | ".SYS Sheriff"
    | "Protektor Sheriff"
    | "Prism II Sheriff"
    | "K/TAC Sheriff"
    | "Magepunk Sheriff"
    | "Minima Sheriff"
    | "Silvanus Sheriff"
    | "Ion Sheriff"
    | "POLYfox Sheriff"
    | "POLYfrog Sheriff"
    | "Protocol 781-A Sheriff"
    | "Lightwave Sheriff"
    | "Sakura Sheriff"
    | "Peacekeeper Sheriff"
    | "Schema Sheriff"
    | "Sentinels of Light Sheriff"
    | "Reaver Sheriff"
    | "Standard Sheriff"
    | "Convex Sheriff"
    | "Varnish Sheriff"
    | "Wasteland Sheriff"
    | "Game Over Sheriff"
    | "Arcane Sheriff"
    | "Death Wish Sheriff";

export type ShortySkin =
    | "Neptune Shorty"
    | "Karabasan Shorty"
    | "Doodle Buds Shorty"
    | "Hivemind Shorty"
    | "Velocity Shorty"
    | "Ruin Shorty"
    | "Monarch Shorty"
    | "Prism II Shorty"
    | "Wunderkind Shorty"
    | "Genesis Shorty"
    | "Oni Shorty"
    | "Snakebite Shorty"
    | "Hue Shift Shorty"
    | "Standard Shorty"
    | "Aerosol Shorty"
    | "Tigris Shorty"
    | "Wayfinder Shorty"
    | "Wasteland Shorty";

export type OperatorSkin =
    | "RGX 11z Pro Operator"
    | "VALORANT GO! Vol. 2 Operator"
    | "Endeavour Operator"
    | "Origin Operator"
    | "Striker Operator"
    | "Red Alert Operator"
    | "Glitchpop Operator"
    | "Elderflame Operator"
    | "Nitro Operator"
    | "Forsaken Operator"
    | "Team Ace Operator"
    | "Infantry Operator"
    | "Prism Operator"
    | "K/TAC Operator"
    | "Luxe Operator"
    | "Magepunk Operator"
    | "Spline Operator"
    | "Minima Operator"
    | "Silvanus Operator"
    | "Genesis Operator"
    | "Ion Operator"
    | "Gravitational Uranium Neuroblaster Operator"
    | "Sentinels of Light Operator"
    | "Reaver Operator"
    | "Tethered Realms Operator"
    | "Cavalier Operator"
    | "Standard Operator"
    | "Aerosol Operator"
    | "Tigris Operator"
    | "Convex Operator";

export type GuardianSkin =
    | "RGX 11z Pro Guardian"
    | "VALORANT GO! Vol. 1 Guardian"
    | "Neptune Guardian"
    | "Gaia's Vengeance Guardian"
    | "Spectrum Guardian"
    | "Nebula Guardian"
    | "Nitro Guardian"
    | "Songsteel Guardian"
    | "Ruin Guardian"
    | "Infantry Guardian"
    | "Hydrodip Guardian"
    | "Prime Guardian"
    | "Ruination Guardian"
    | "Magepunk Guardian"
    | "Galleria Guardian"
    | "Oni Guardian"
    | "Aero Guardian"
    | "POLYfox Guardian"
    | "Jigsaw Guardian"
    | "Reaver Guardian"
    | "Sovereign Guardian"
    | "Tethered Realms Guardian"
    | "Recon Guardian"
    | "Infinity Guardian"
    | "Standard Guardian"
    | "Ego Guardian";

export type MarshalSkin =
    | "Gaia's Vengeance Marshal"
    | "Doodle Buds Marshal"
    | "Songsteel Marshal"
    | "Ruin Marshal"
    | "Monarch Marshal"
    | "Avalanche Marshal"
    | "Couture Marshal"
    | "Magepunk Marshal"
    | "Coalition: Cobra Marshal"
    | "Galleria Marshal"
    | "POLYfrog Marshal"
    | "Divine Swine Marshal"
    | "Artisan Marshal"
    | "Sovereign Marshal"
    | "Standard Marshal"
    | "Wasteland Marshal"
    | "Winterwunderland Marshal";

export type SpectreSkin =
    | "RGX 11z Pro Spectre"
    | "VALORANT GO! Vol. 1 Spectre"
    | "Neptune Spectre"
    | "Striker Spectre"
    | "Radiant Crisis 001 Spectre"
    | "Singularity Spectre"
    | "Hivemind Spectre"
    | "Forsaken Spectre"
    | "Velocity Spectre"
    | "Infantry Spectre"
    | "Horizon Spectre"
    | "Prime Spectre"
    | "Avalanche Spectre"
    | "Prism Spectre"
    | "Serenity Spectre"
    | "Ruination Spectre"
    | "Kingdom Spectre"
    | "Luxe Spectre"
    | "Magepunk Spectre"
    | "Spline Spectre"
    | "Minima Spectre"
    | "Hue Shift Spectre"
    | "Aero Spectre"
    | "POLYfrog Spectre"
    | "Protocol 781-A Spectre"
    | "Gravitational Uranium Neuroblaster Spectre"
    | "Recon Spectre"
    | "Infinity Spectre"
    | "Standard Spectre"
    | "Tigris Spectre"
    | "Convex Spectre"
    | "BlastX Spectre"
    | "Wasteland Spectre";

export type StingerSkin =
    | "RGX 11z Pro Stinger"
    | "Aristocrat Stinger"
    | "Red Alert Stinger"
    | "Doodle Buds Stinger"
    | "Surge Stinger"
    | ".SYS Stinger"
    | "Prism II Stinger"
    | "Couture Stinger"
    | "Silvanus Stinger"
    | "Sensation Stinger"
    | "Sakura Stinger"
    | "Schema Stinger"
    | "Lycan's Bane Stinger"
    | "Sovereign Stinger"
    | "Cavalier Stinger"
    | "Standard Stinger"
    | "Depths Stinger"
    | "Ego Stinger"
    | "Varnish Stinger";

export type KnifeSkin =
    | "RGX 11z Pro Blade"
    | "RGX 11z Pro Firefly"
    | "VALORANT GO! Vol. 1 Knife"
    | "Yoru's Stylish Butterfly Comb"
    | "Neptune Anchor"
    | "Gaia's Wrath"
    | "Waveform"
    | "Champions 2021 Karambit"
    | "Origin Crescent Blade"
    | "Striker Knife"
    | "Radiant Crisis 001 Baseball Bat"
    | "Nebula Knife"
    | "Hack"
    | "Glitchpop Dagger"
    | "Glitchpop Axe"
    | "Elderflame Dagger"
    | "Singularity Knife"
    | "Songsteel"
    | "Hivemind Sword"
    | "Forsaken Ritual Blade"
    | "Velocity Karambit"
    | "Ruin Dagger"
    | ".SYS Melee"
    | "Prime Axe"
    | "Prime//2.0 Karambit"
    | "Outpost Melee"
    | "Prism Knife"
    | "Prism III Axe"
    | "Broken Blade of the Ruined King"
    | "Kingdom Knife"
    | "K/TAC Blade"
    | "Smite Knife"
    | "Catrina"
    | "Celestial Fan"
    | "Luxe Knife"
    | "Magepunk Electroblade"
    | "Magepunk Shock Gauntlet"
    | "Spline Dagger"
    | "Genesis Arc"
    | "Ion Energy Sword"
    | "Oni Claw"
    | "Artisan Foil"
    | "Personal Administrative Melee Unit"
    | "Gravitational Uranium Neuroblaster Baton"
    | "Snowfall Wand"
    | "Relic of the Sentinel"
    | "Reaver Knife"
    | "Sovereign Sword"
    | "Prosperity"
    | "Recon Balisong"
    | "Titanmail Mace"
    | "Melee"
    | "Hu Else"
    | "Ego Knife"
    | "BlastX Polymer KnifeTech Coated Knife"
    | "Winterwunderland Candy Cane";
