/* FILE GENERATED AUTOMATICALLY */

export type SprayType =
    | "Caught on Camera Spray"
    | "Chicken Out Spray"
    | "Defy the Limits Spray"
    | "G.O.A.T. Spray"
    | "Sad Crab Spray"
    | "No Time Spray"
    | "No Toxicity Spray"
    | "Dark Side Beyond Spray"
    | "Dap Team Spray"
    | "This is Also Fine Spray"
    | "Little Onion Lad Spray"
    | "Cheaters Never Prosper Spray"
    | "Wanted: Tactibunny Spray"
    | "8-bit VALORANT Spray"
    | "GGWP Spray"
    | "Mic Drop Spray"
    | "Step Under Here Spray"
    | "No Op Spray"
    | "Piece of Cake Spray"
    | "Octorave Spray"
    | "Pick My Strat Spray"
    | "Stellar Dendrite Spray"
    | "Thumbs Up Spray"
    | "Stay Safe, Wash Your Hands Spray"
    | "Spectrum Spray"
    | "Breach Spray"
    | "K.O. Spray"
    | "Guns Out Spray"
    | "FTW Spray"
    | "Camper Spray"
    | "Excuse Me? Spray"
    | "Cheesy Shot Spray"
    | "Raze Spray"
    | "BoomShaka Spray"
    | "Bombshell Spray"
    | "Explorgi Spray"
    | "Danger Spray"
    | "VALORANT Spray"
    | "Elderflame Spray"
    | "Spicy Spray"
    | "Hershey Pup Spray"
    | "Blueberry Spray"
    | "Choose my Weapon Spray"
    | "Glitch Out Chicken Spray"
    | "Make 'em Dance Spray"
    | "EZ Spray"
    | "Going C Spray"
    | "<3 Spray"
    | "Lit for 140 Spray"
    | "Faces in Places Spray"
    | "No Shorty Spray"
    | "Radianite Hazard Spray"
    | "What was that? Spray"
    | "Alas, poor Robot! Spray"
    | "Make Some Noise Spray"
    | "Chill Out Spray"
    | "Is This A Drone? Spray"
    | "Shhh! Spray"
    | "Do Not Enter Spray"
    | "Dumpster Fire Spray"
    | "/FF Spray"
    | "Epilogue: Super! Spray"
    | "Embarrassing! Spray"
    | "LAG! Spray"
    | "MY EYES! Spray"
    | "Happy Frog Spray"
    | "Revive Me, Jett! Spray"
    | "Super! Spray"
    | "¯\\_(ツ)_/¯ Spray"
    | "Nope Spray"
    | "Approved! Spray"
    | "Lobster? Spray"
    | "Theo's Great Escape Spray"
    | "Bunny Hop Spray"
    | "Without a Trace Spray"
    | "Dabbing Dan Spray"
    | "Epilogue: Dabbing Dan Spray"
    | "Comedy and the Tragedy Spray"
    | "Songsteel Spray"
    | "Hang in There, Mance Spray"
    | "Nice Save Spray"
    | "Be Gone! Spray"
    | "No Odin Spray"
    | "This is Also Also Fine Spray"
    | "300 Spray"
    | "Walk! Don't Run Spray"
    | "Hardstuck Spray"
    | "Clutch or Kick Spray"
    | "Cracked Spray"
    | "Epilogue: Cracked Spray"
    | "Greatly Decreased? Spray"
    | "Sands of Time Spray"
    | "Killjoy! I Choose You! Spray"
    | "Max Money Spray"
    | "No Guardian Spray"
    | "No Pen Spray"
    | "Sand Sculpture Spray"
    | "Sova Says Sorry Spray"
    | "Surprised Penguin Spray"
    | "Pump Action Spray"
    | "Too Heavy Spray"
    | "Greatly Increased? Spray"
    | "Promises Kept Spray"
    | "Yikes Spray"
    | "Hooked Spray"
    | "Crispy Spray"
    | "Does Not Compute Spray"
    | "Hold Up Spray"
    | "Love > Hate Spray"
    | "No Judge Spray"
    | "Nice Try! Spray"
    | "OTL Spray"
    | "Artisan Spray"
    | "Trust in My Healing Spray"
    | "This is Not Fine Spray"
    | "To the Moon Spray"
    | "Not Impressed Spray"
    | "Fist Bump Spray"
    | "GG Shooter Spray"
    | "GLHF Spray"
    | "KAY/O Spray"
    | "Drained Spray"
    | "Training Bot Spray"
    | "Wild Life Spray"
    | "On Your Trail Spray"
    | "Skye Spray"
    | "Cypher Spray"
    | "The Seeker Spray"
    | "I See You Spray"
    | "Lethal Crosshair Spray"
    | "Sova Spray"
    | "Take Flight Spray"
    | "On Target Spray"
    | "Prime Brick Spray"
    | "Killjoy Spray"
    | "Variable Removed Spray"
    | "Don't Cross Me Spray"
    | "Lights Out Spray"
    | "Celestial Spray"
    | "Just Business Spray"
    | "Give Back Spray"
    | "Pity Party Spray"
    | "Octo Attack 2 Spray"
    | "Pick Your Poison Spray"
    | "Deadly Venom Spray"
    | "Viper Spray"
    | "Phoenix Spray"
    | "Claim the Crown Spray"
    | "Spotlight Spray"
    | "Too Easy Spray"
    | "Astral Plane Spray"
    | "Astra Spray"
    | "Galaxy Brain Spray"
    | "Salt Shaker Spray"
    | "Brimstone Spray"
    | "The Big One Spray"
    | "Getting Reps  Spray"
    | "VALORANT GO! Vol. 1 Cypher Spray"
    | "VALORANT GO! Vol. 1 Jett Spray"
    | "VALORANT GO! Vol. 1 Killjoy Spray"
    | "VALORANT GO! Vol. 1 Reyna Spray"
    | "VALORANT GO! Vol. 1 Sage Spray"
    | "VALORANT GO! Vol. 2 Phoenix Spray"
    | "VALORANT GO! Vol. 2 Raze Spray"
    | "VALORANT GO! Vol. 2 Sova Spray"
    | "VALORANT GO! Vol. 2 Viper Spray"
    | "VALORANT GO! Vol. 2 Yoru Spray"
    | "Origin Spray"
    | "Glitchpop Spray"
    | "Glitchpop, EP 2 Spray"
    | "Singularity Spray"
    | "Forsaken Spray"
    | "Ruin Spray"
    | "Prime//2.0 Spray"
    | "Ruination Spray"
    | "Magepunk Spray"
    | "Spline Spray"
    | "Ion Spray"
    | "Oni Spray"
    | "Gravitational Uranium Neuroblaster Spray"
    | "Sentinels of Light Spray"
    | "Reaver Spray"
    | "Ego Spray"
    | "BlastX Spray"
    | "Sovereign Spray"
    | "Clip It Spray"
    | "Who's Next Spray"
    | "Sharp Spray"
    | "Yoru Spray"
    | "200 IQ Spray"
    | "Tactibear Spray"
    | "Sage Spray"
    | "All Good Spray"
    | "Pulse Check Spray"
    | "V for VALORANT Spray"
    | "Can't Teach That Spray"
    | "Reyna Spray"
    | "Leer Spray"
    | "Marked for Death Spray"
    | "Vandal Life Spray"
    | "Omen Spray"
    | "It Hunts Spray"
    | "Dark Focus Spray"
    | "Jett Spray"
    | "Watch This Spray"
    | "You Better Run Spray";
